        // Copyright (C) 2025-2026 Demerzel Solutions Limited (Nethermind)
using System;

        class H {
            [ThreadStatic] public static int F0;
    [ThreadStatic] public static int F1;
    [ThreadStatic] public static int F2;
    [ThreadStatic] public static int F3;
    [ThreadStatic] public static int F4;
    [ThreadStatic] public static int F5;
    [ThreadStatic] public static int F6;
    [ThreadStatic] public static int F7;
    [ThreadStatic] public static int F8;
    [ThreadStatic] public static int F9;
    [ThreadStatic] public static int F10;
    [ThreadStatic] public static int F11;
    [ThreadStatic] public static int F12;
    [ThreadStatic] public static int F13;
    [ThreadStatic] public static int F14;
    [ThreadStatic] public static int F15;
    [ThreadStatic] public static int F16;
    [ThreadStatic] public static int F17;
    [ThreadStatic] public static int F18;
    [ThreadStatic] public static int F19;
    [ThreadStatic] public static int F20;
    [ThreadStatic] public static int F21;
    [ThreadStatic] public static int F22;
    [ThreadStatic] public static int F23;
    [ThreadStatic] public static int F24;
    [ThreadStatic] public static int F25;
    [ThreadStatic] public static int F26;
    [ThreadStatic] public static int F27;
    [ThreadStatic] public static int F28;
    [ThreadStatic] public static int F29;
    [ThreadStatic] public static int F30;
    [ThreadStatic] public static int F31;
    [ThreadStatic] public static int F32;
    [ThreadStatic] public static int F33;
    [ThreadStatic] public static int F34;
    [ThreadStatic] public static int F35;
    [ThreadStatic] public static int F36;
    [ThreadStatic] public static int F37;
    [ThreadStatic] public static int F38;
    [ThreadStatic] public static int F39;
    [ThreadStatic] public static int F40;
    [ThreadStatic] public static int F41;
    [ThreadStatic] public static int F42;
    [ThreadStatic] public static int F43;
    [ThreadStatic] public static int F44;
    [ThreadStatic] public static int F45;
    [ThreadStatic] public static int F46;
    [ThreadStatic] public static int F47;
    [ThreadStatic] public static int F48;
    [ThreadStatic] public static int F49;
        }

        class Program
        {
            static int Main()
            {
                H.F0 = 0;
        H.F1 = 1;
        H.F2 = 2;
        H.F3 = 3;
        H.F4 = 4;
        H.F5 = 5;
        H.F6 = 6;
        H.F7 = 7;
        H.F8 = 8;
        H.F9 = 9;
        H.F10 = 10;
        H.F11 = 11;
        H.F12 = 12;
        H.F13 = 13;
        H.F14 = 14;
        H.F15 = 15;
        H.F16 = 16;
        H.F17 = 17;
        H.F18 = 18;
        H.F19 = 19;
        H.F20 = 20;
        H.F21 = 21;
        H.F22 = 22;
        H.F23 = 23;
        H.F24 = 24;
        H.F25 = 25;
        H.F26 = 26;
        H.F27 = 27;
        H.F28 = 28;
        H.F29 = 29;
        H.F30 = 30;
        H.F31 = 31;
        H.F32 = 32;
        H.F33 = 33;
        H.F34 = 34;
        H.F35 = 35;
        H.F36 = 36;
        H.F37 = 37;
        H.F38 = 38;
        H.F39 = 39;
        H.F40 = 40;
        H.F41 = 41;
        H.F42 = 42;
        H.F43 = 43;
        H.F44 = 44;
        H.F45 = 45;
        H.F46 = 46;
        H.F47 = 47;
        H.F48 = 48;
        H.F49 = 49;
                if (H.F0 != 0) return 1;
        if (H.F1 != 1) return 1;
        if (H.F2 != 2) return 1;
        if (H.F3 != 3) return 1;
        if (H.F4 != 4) return 1;
        if (H.F5 != 5) return 1;
        if (H.F6 != 6) return 1;
        if (H.F7 != 7) return 1;
        if (H.F8 != 8) return 1;
        if (H.F9 != 9) return 1;
        if (H.F10 != 10) return 1;
        if (H.F11 != 11) return 1;
        if (H.F12 != 12) return 1;
        if (H.F13 != 13) return 1;
        if (H.F14 != 14) return 1;
        if (H.F15 != 15) return 1;
        if (H.F16 != 16) return 1;
        if (H.F17 != 17) return 1;
        if (H.F18 != 18) return 1;
        if (H.F19 != 19) return 1;
        if (H.F20 != 20) return 1;
        if (H.F21 != 21) return 1;
        if (H.F22 != 22) return 1;
        if (H.F23 != 23) return 1;
        if (H.F24 != 24) return 1;
        if (H.F25 != 25) return 1;
        if (H.F26 != 26) return 1;
        if (H.F27 != 27) return 1;
        if (H.F28 != 28) return 1;
        if (H.F29 != 29) return 1;
        if (H.F30 != 30) return 1;
        if (H.F31 != 31) return 1;
        if (H.F32 != 32) return 1;
        if (H.F33 != 33) return 1;
        if (H.F34 != 34) return 1;
        if (H.F35 != 35) return 1;
        if (H.F36 != 36) return 1;
        if (H.F37 != 37) return 1;
        if (H.F38 != 38) return 1;
        if (H.F39 != 39) return 1;
        if (H.F40 != 40) return 1;
        if (H.F41 != 41) return 1;
        if (H.F42 != 42) return 1;
        if (H.F43 != 43) return 1;
        if (H.F44 != 44) return 1;
        if (H.F45 != 45) return 1;
        if (H.F46 != 46) return 1;
        if (H.F47 != 47) return 1;
        if (H.F48 != 48) return 1;
        if (H.F49 != 49) return 1;
                Console.WriteLine("tls_stress: wide_class_50 ok");
                return 0;
            }
        }
