// Copyright (C) 2026 Demerzel Solutions Limited (Nethermind)
// GENERATED by softfloat/gen_tests.py - do not edit by hand.
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

static unsafe class T
{
    [DllImport("__Internal")]
    static extern void sys_write(uint fd, byte* p, nuint n);

    static void P(string s)
    {
        byte[] b = new byte[s.Length + 1];
        for (int i = 0; i < s.Length; i++) b[i] = (byte)s[i];
        b[s.Length] = (byte)10;
        fixed (byte* p = b) sys_write(1, p, (nuint)b.Length);
    }

    static int F_;

    static void Ck(string n, string a, string e)
    {
        if (a != e) { F_++; P("FAIL " + n + ": " + a + " != " + e); }
    }

    static double D(long b) => BitConverter.Int64BitsToDouble(b);
    static float  F(int b)  => BitConverter.Int32BitsToSingle(b);
    static string H(double d) => double.IsNaN(d) ? "nan" : "0x" + BitConverter.DoubleToInt64Bits(d).ToString("x16");
    static string Hf(float f) => float.IsNaN(f) ? "nan" : "0x" + BitConverter.SingleToInt32Bits(f).ToString("x8");

    [MethodImpl(MethodImplOptions.NoInlining)] static double Id(double x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static float  If(float x) => x;

    [MethodImpl(MethodImplOptions.NoInlining)]
    static double Sum10(double a, double b, double c, double d, double e,
                        double f, double g, double h, double i, double j)
        => a + b + c + d + e + f + g + h + i + j;

    [MethodImpl(MethodImplOptions.NoInlining)]
    static float MixIF(int a, float b, long c, double d, float e)
        => (float)(a + b + c + d + e);

    struct Pair { public double X; public double Y; }
    struct FPair { public float X; public float Y; }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static Pair MkPair(double x, double y) { Pair p; p.X = x; p.Y = y; return p; }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static double PairDot(Pair p, Pair q) => p.X * q.X + p.Y * q.Y;

    [MethodImpl(MethodImplOptions.NoInlining)]
    static FPair MkFPair(float x, float y) { FPair p; p.X = x; p.Y = y; return p; }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static void OutRef(double a, out double o, ref double r) { o = a * 2.0; r += a; }

    static double SField = 1.25;
    class Holder { public double V = 2.5; public float FV = 0.5f; }

    static void Run()
    {
        Ck("sum10", H(Sum10(Id(0.1), Id(0.2), Id(0.3), Id(0.4), Id(0.5), Id(0.6), Id(0.7), Id(0.8), Id(0.9), Id(1.0))), "0x4016000000000000");
        Ck("mixif", Hf(MixIF(3, If(0.5f), 7L, Id(0.25), If(1.5f))), "0x41440000");
        var p = MkPair(Id(1.5), Id(-2.5));
        var q = MkPair(Id(3.0), Id(4.0));
        Ck("pairdot", H(PairDot(p, q)), "0xc016000000000000");
        var fp = MkFPair(If(1.5f), If(2.5f));
        Ck("fpair", Hf(fp.X + fp.Y), "0x40800000");
        double o, r = 10.0;
        OutRef(Id(3.5), out o, ref r);
        Ck("outv", H(o), "0x401c000000000000");
        Ck("refv", H(r), "0x402b000000000000");
        Ck("sfield", H(SField * 2.0), "0x4004000000000000");
        var hd = new Holder();
        Ck("hfield", H(hd.V + 0.25), "0x4006000000000000");
        Ck("hffield", Hf(hd.FV * 3.0f), "0x3fc00000");
        double[] arr = new double[] { 0.1, 0.2, 0.3, 0.4 };
        double asum = 0.0;
        foreach (double v in arr) asum += v;
        Ck("arrsum", H(asum), "0x3ff0000000000000");
        object box = Id(1.25);
        Ck("box", H((double)box + 1.0), "0x4002000000000000");
        double? nd = Id(0.75);
        Ck("nullable", H(nd.Value * 4.0), "0x4008000000000000");
    }

    static int Main()
    {
        Run();
        P(F_ == 0 ? "ALL PASS" : "FAILURES: " + F_);
        return F_ == 0 ? 0 : 1;
    }
}
