// Copyright (C) 2026 Demerzel Solutions Limited (Nethermind)
// GENERATED by softfloat/gen_tests.py - do not edit by hand.
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

static unsafe class T
{
    [DllImport("__Internal")]
    static extern void sys_write(uint fd, byte* p, nuint n);

    static void P(string s)
    {
        byte[] b = new byte[s.Length + 1];
        for (int i = 0; i < s.Length; i++) b[i] = (byte)s[i];
        b[s.Length] = (byte)10;
        fixed (byte* p = b) sys_write(1, p, (nuint)b.Length);
    }

    static int F_;

    static void Ck(string n, string a, string e)
    {
        if (a != e) { F_++; P("FAIL " + n + ": " + a + " != " + e); }
    }

    static double D(long b) => BitConverter.Int64BitsToDouble(b);
    static float  F(int b)  => BitConverter.Int32BitsToSingle(b);
    static string H(double d) => double.IsNaN(d) ? "nan" : "0x" + BitConverter.DoubleToInt64Bits(d).ToString("x16");
    static string Hf(float f) => float.IsNaN(f) ? "nan" : "0x" + BitConverter.SingleToInt32Bits(f).ToString("x8");

    [MethodImpl(MethodImplOptions.NoInlining)] static double Id(double x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static float  If(float x) => x;
    static void Run()
    {
        bool ovf;
        ovf = false; try { var r_0 = checked((int)Id(D(unchecked((long)0x0000000000000000)) /* 0.0 */)); if (r_0.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_0", ovf.ToString(), "False");
        ovf = false; try { var r_1 = checked((int)Id(D(unchecked((long)0x3ff8000000000000)) /* 1.5 */)); if (r_1.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_1", ovf.ToString(), "False");
        ovf = false; try { var r_2 = checked((int)Id(D(unchecked((long)0xbff8000000000000)) /* -1.5 */)); if (r_2.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_2", ovf.ToString(), "False");
        ovf = false; try { var r_3 = checked((int)Id(D(unchecked((long)0x41dfffffff800000)) /* 2147483646.0 */)); if (r_3.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_3", ovf.ToString(), "False");
        ovf = false; try { var r_4 = checked((int)Id(D(unchecked((long)0x41e0000000000000)) /* 2147483648.0 */)); if (r_4.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_4", ovf.ToString(), "True");
        ovf = false; try { var r_5 = checked((int)Id(D(unchecked((long)0xc1e0000000200000)) /* -2147483649.0 */)); if (r_5.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_5", ovf.ToString(), "True");
        ovf = false; try { var r_6 = checked((int)Id(D(unchecked((long)0x41f0000000000000)) /* 4294967296.0 */)); if (r_6.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_6", ovf.ToString(), "True");
        ovf = false; try { var r_7 = checked((int)Id(D(unchecked((long)0x43e02207973f6440)) /* 9.3e+18 */)); if (r_7.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_7", ovf.ToString(), "True");
        ovf = false; try { var r_8 = checked((int)Id(D(unchecked((long)0x43f07ad8f556c6c0)) /* 1.9e+19 */)); if (r_8.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_8", ovf.ToString(), "True");
        ovf = false; try { var r_9 = checked((int)Id(D(unchecked((long)0xc3e02207973f6440)) /* -9.3e+18 */)); if (r_9.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_9", ovf.ToString(), "True");
        ovf = false; try { var r_10 = checked((int)Id(D(unchecked((long)0x7ff8000000000000)))); if (r_10.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_10", ovf.ToString(), "True");
        ovf = false; try { var r_11 = checked((int)Id(D(unchecked((long)0x7ff0000000000000)))); if (r_11.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_11", ovf.ToString(), "True");
        ovf = false; try { var r_12 = checked((int)Id(D(unchecked((long)0xfff0000000000000)))); if (r_12.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_12", ovf.ToString(), "True");
        ovf = false; try { var r_13 = checked((int)Id(D(unchecked((long)0x406fe00000000000)) /* 255.0 */)); if (r_13.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_int_13", ovf.ToString(), "False");
        ovf = false; try { var r_14 = checked((uint)Id(D(unchecked((long)0x0000000000000000)) /* 0.0 */)); if (r_14.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_14", ovf.ToString(), "False");
        ovf = false; try { var r_15 = checked((uint)Id(D(unchecked((long)0x3ff8000000000000)) /* 1.5 */)); if (r_15.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_15", ovf.ToString(), "False");
        ovf = false; try { var r_16 = checked((uint)Id(D(unchecked((long)0xbff8000000000000)) /* -1.5 */)); if (r_16.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_16", ovf.ToString(), "True");
        ovf = false; try { var r_17 = checked((uint)Id(D(unchecked((long)0x41dfffffff800000)) /* 2147483646.0 */)); if (r_17.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_17", ovf.ToString(), "False");
        ovf = false; try { var r_18 = checked((uint)Id(D(unchecked((long)0x41e0000000000000)) /* 2147483648.0 */)); if (r_18.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_18", ovf.ToString(), "False");
        ovf = false; try { var r_19 = checked((uint)Id(D(unchecked((long)0xc1e0000000200000)) /* -2147483649.0 */)); if (r_19.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_19", ovf.ToString(), "True");
        ovf = false; try { var r_20 = checked((uint)Id(D(unchecked((long)0x41f0000000000000)) /* 4294967296.0 */)); if (r_20.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_20", ovf.ToString(), "True");
        ovf = false; try { var r_21 = checked((uint)Id(D(unchecked((long)0x43e02207973f6440)) /* 9.3e+18 */)); if (r_21.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_21", ovf.ToString(), "True");
        ovf = false; try { var r_22 = checked((uint)Id(D(unchecked((long)0x43f07ad8f556c6c0)) /* 1.9e+19 */)); if (r_22.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_22", ovf.ToString(), "True");
        ovf = false; try { var r_23 = checked((uint)Id(D(unchecked((long)0xc3e02207973f6440)) /* -9.3e+18 */)); if (r_23.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_23", ovf.ToString(), "True");
        ovf = false; try { var r_24 = checked((uint)Id(D(unchecked((long)0x7ff8000000000000)))); if (r_24.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_24", ovf.ToString(), "True");
        ovf = false; try { var r_25 = checked((uint)Id(D(unchecked((long)0x7ff0000000000000)))); if (r_25.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_25", ovf.ToString(), "True");
        ovf = false; try { var r_26 = checked((uint)Id(D(unchecked((long)0xfff0000000000000)))); if (r_26.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_26", ovf.ToString(), "True");
        ovf = false; try { var r_27 = checked((uint)Id(D(unchecked((long)0x406fe00000000000)) /* 255.0 */)); if (r_27.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_uint_27", ovf.ToString(), "False");
        ovf = false; try { var r_28 = checked((long)Id(D(unchecked((long)0x0000000000000000)) /* 0.0 */)); if (r_28.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_28", ovf.ToString(), "False");
        ovf = false; try { var r_29 = checked((long)Id(D(unchecked((long)0x3ff8000000000000)) /* 1.5 */)); if (r_29.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_29", ovf.ToString(), "False");
        ovf = false; try { var r_30 = checked((long)Id(D(unchecked((long)0xbff8000000000000)) /* -1.5 */)); if (r_30.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_30", ovf.ToString(), "False");
        ovf = false; try { var r_31 = checked((long)Id(D(unchecked((long)0x41dfffffff800000)) /* 2147483646.0 */)); if (r_31.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_31", ovf.ToString(), "False");
        ovf = false; try { var r_32 = checked((long)Id(D(unchecked((long)0x41e0000000000000)) /* 2147483648.0 */)); if (r_32.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_32", ovf.ToString(), "False");
        ovf = false; try { var r_33 = checked((long)Id(D(unchecked((long)0xc1e0000000200000)) /* -2147483649.0 */)); if (r_33.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_33", ovf.ToString(), "False");
        ovf = false; try { var r_34 = checked((long)Id(D(unchecked((long)0x41f0000000000000)) /* 4294967296.0 */)); if (r_34.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_34", ovf.ToString(), "False");
        ovf = false; try { var r_35 = checked((long)Id(D(unchecked((long)0x43e02207973f6440)) /* 9.3e+18 */)); if (r_35.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_35", ovf.ToString(), "True");
        ovf = false; try { var r_36 = checked((long)Id(D(unchecked((long)0x43f07ad8f556c6c0)) /* 1.9e+19 */)); if (r_36.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_36", ovf.ToString(), "True");
        ovf = false; try { var r_37 = checked((long)Id(D(unchecked((long)0xc3e02207973f6440)) /* -9.3e+18 */)); if (r_37.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_37", ovf.ToString(), "True");
        ovf = false; try { var r_38 = checked((long)Id(D(unchecked((long)0x7ff8000000000000)))); if (r_38.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_38", ovf.ToString(), "True");
        ovf = false; try { var r_39 = checked((long)Id(D(unchecked((long)0x7ff0000000000000)))); if (r_39.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_39", ovf.ToString(), "True");
        ovf = false; try { var r_40 = checked((long)Id(D(unchecked((long)0xfff0000000000000)))); if (r_40.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_40", ovf.ToString(), "True");
        ovf = false; try { var r_41 = checked((long)Id(D(unchecked((long)0x406fe00000000000)) /* 255.0 */)); if (r_41.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_long_41", ovf.ToString(), "False");
        ovf = false; try { var r_42 = checked((ulong)Id(D(unchecked((long)0x0000000000000000)) /* 0.0 */)); if (r_42.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_42", ovf.ToString(), "False");
        ovf = false; try { var r_43 = checked((ulong)Id(D(unchecked((long)0x3ff8000000000000)) /* 1.5 */)); if (r_43.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_43", ovf.ToString(), "False");
        ovf = false; try { var r_44 = checked((ulong)Id(D(unchecked((long)0xbff8000000000000)) /* -1.5 */)); if (r_44.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_44", ovf.ToString(), "True");
        ovf = false; try { var r_45 = checked((ulong)Id(D(unchecked((long)0x41dfffffff800000)) /* 2147483646.0 */)); if (r_45.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_45", ovf.ToString(), "False");
        ovf = false; try { var r_46 = checked((ulong)Id(D(unchecked((long)0x41e0000000000000)) /* 2147483648.0 */)); if (r_46.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_46", ovf.ToString(), "False");
        ovf = false; try { var r_47 = checked((ulong)Id(D(unchecked((long)0xc1e0000000200000)) /* -2147483649.0 */)); if (r_47.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_47", ovf.ToString(), "True");
        ovf = false; try { var r_48 = checked((ulong)Id(D(unchecked((long)0x41f0000000000000)) /* 4294967296.0 */)); if (r_48.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_48", ovf.ToString(), "False");
        ovf = false; try { var r_49 = checked((ulong)Id(D(unchecked((long)0x43e02207973f6440)) /* 9.3e+18 */)); if (r_49.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_49", ovf.ToString(), "False");
        ovf = false; try { var r_50 = checked((ulong)Id(D(unchecked((long)0x43f07ad8f556c6c0)) /* 1.9e+19 */)); if (r_50.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_50", ovf.ToString(), "True");
        ovf = false; try { var r_51 = checked((ulong)Id(D(unchecked((long)0xc3e02207973f6440)) /* -9.3e+18 */)); if (r_51.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_51", ovf.ToString(), "True");
        ovf = false; try { var r_52 = checked((ulong)Id(D(unchecked((long)0x7ff8000000000000)))); if (r_52.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_52", ovf.ToString(), "True");
        ovf = false; try { var r_53 = checked((ulong)Id(D(unchecked((long)0x7ff0000000000000)))); if (r_53.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_53", ovf.ToString(), "True");
        ovf = false; try { var r_54 = checked((ulong)Id(D(unchecked((long)0xfff0000000000000)))); if (r_54.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_54", ovf.ToString(), "True");
        ovf = false; try { var r_55 = checked((ulong)Id(D(unchecked((long)0x406fe00000000000)) /* 255.0 */)); if (r_55.ToString() == "~") P(""); } catch (OverflowException) { ovf = true; }
        Ck("ck_ulong_55", ovf.ToString(), "False");
    }

    static int Main()
    {
        Run();
        P(F_ == 0 ? "ALL PASS" : "FAILURES: " + F_);
        return F_ == 0 ? 0 : 1;
    }
}
