// Copyright (C) 2026 Demerzel Solutions Limited (Nethermind)
// GENERATED by softfloat/gen_tests.py - do not edit by hand.
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

static unsafe class T
{
    [DllImport("__Internal")]
    static extern void sys_write(uint fd, byte* p, nuint n);

    static void P(string s)
    {
        byte[] b = new byte[s.Length + 1];
        for (int i = 0; i < s.Length; i++) b[i] = (byte)s[i];
        b[s.Length] = (byte)10;
        fixed (byte* p = b) sys_write(1, p, (nuint)b.Length);
    }

    static int F_;

    static void Ck(string n, string a, string e)
    {
        if (a != e) { F_++; P("FAIL " + n + ": " + a + " != " + e); }
    }

    static double D(long b) => BitConverter.Int64BitsToDouble(b);
    static float  F(int b)  => BitConverter.Int32BitsToSingle(b);
    static string H(double d) => double.IsNaN(d) ? "nan" : "0x" + BitConverter.DoubleToInt64Bits(d).ToString("x16");
    static string Hf(float f) => float.IsNaN(f) ? "nan" : "0x" + BitConverter.SingleToInt32Bits(f).ToString("x8");

    [MethodImpl(MethodImplOptions.NoInlining)] static double Id(double x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static float  If(float x) => x;
    static void Run()
    {
        Ck("d2i_0", ((int)Id(D(unchecked((long)0x0000000000000000)) /* 0.0 */)).ToString(), "0");
        Ck("d2i_1", ((int)Id(D(unchecked((long)0x8000000000000000)) /* -0.0 */)).ToString(), "0");
        Ck("d2i_2", ((int)Id(D(unchecked((long)0x3ff0000000000000)) /* 1.0 */)).ToString(), "1");
        Ck("d2i_3", ((int)Id(D(unchecked((long)0xbff0000000000000)) /* -1.0 */)).ToString(), "-1");
        Ck("d2i_4", ((int)Id(D(unchecked((long)0x3fe0000000000000)) /* 0.5 */)).ToString(), "0");
        Ck("d2i_5", ((int)Id(D(unchecked((long)0x4000000000000000)) /* 2.0 */)).ToString(), "2");
        Ck("d2i_6", ((int)Id(D(unchecked((long)0x3fb999999999999a)) /* 0.1 */)).ToString(), "0");
        Ck("d2i_7", ((int)Id(D(unchecked((long)0x400921fb54442d18)) /* 3.141592653589793 */)).ToString(), "3");
        Ck("d2i_8", ((int)Id(D(unchecked((long)0x431550f7dca70000)) /* 1500000000000000.0 */)).ToString(), "2147483647");
        Ck("d2i_9", ((int)Id(D(unchecked((long)0xc01d000000000000)) /* -7.25 */)).ToString(), "-7");
        Ck("d2i_10", ((int)Id(D(unchecked((long)0x7fe1ccf385ebc8a0)) /* 1e+308 */)).ToString(), "2147483647");
        Ck("d2i_11", ((int)Id(D(unchecked((long)0xffe1ccf385ebc8a0)) /* -1e+308 */)).ToString(), "-2147483648");
        Ck("d2i_12", ((int)Id(D(unchecked((long)0x0000000000000001)) /* 5e-324 */)).ToString(), "0");
        Ck("d2i_13", ((int)Id(D(unchecked((long)0x0010000000000000)) /* 2.2250738585072014e-308 */)).ToString(), "0");
        Ck("d2i_14", ((int)Id(D(unchecked((long)0x7ff0000000000000)))).ToString(), "2147483647");
        Ck("d2i_15", ((int)Id(D(unchecked((long)0xfff0000000000000)))).ToString(), "-2147483648");
        Ck("d2i_16", ((int)Id(D(unchecked((long)0x7ff8000000000000)))).ToString(), "0");
        Ck("d2i_17", ((int)Id(D(unchecked((long)0x41dfffffffa00000)) /* 2147483646.5 */)).ToString(), "2147483646");
        Ck("d2i_18", ((int)Id(D(unchecked((long)0x41dfffffffc00000)) /* 2147483647.0 */)).ToString(), "2147483647");
        Ck("d2i_19", ((int)Id(D(unchecked((long)0x41e0000000000000)) /* 2147483648.0 */)).ToString(), "2147483647");
        Ck("d2i_20", ((int)Id(D(unchecked((long)0xc1e0000000000000)) /* -2147483648.0 */)).ToString(), "-2147483648");
        Ck("d2i_21", ((int)Id(D(unchecked((long)0xc1e0000000200000)) /* -2147483649.0 */)).ToString(), "-2147483648");
        Ck("d2i_22", ((int)Id(D(unchecked((long)0x41efffffffe00000)) /* 4294967295.0 */)).ToString(), "2147483647");
        Ck("d2i_23", ((int)Id(D(unchecked((long)0x41f0000000000000)) /* 4294967296.0 */)).ToString(), "2147483647");
        Ck("d2i_24", ((int)Id(D(unchecked((long)0x43dfffffffffffff)) /* 9.223372036854775e+18 */)).ToString(), "2147483647");
        Ck("d2i_25", ((int)Id(D(unchecked((long)0xc3e0000000000000)) /* -9.223372036854776e+18 */)).ToString(), "-2147483648");
        Ck("d2i_26", ((int)Id(D(unchecked((long)0x43f0000000000000)) /* 1.8446744073709552e+19 */)).ToString(), "2147483647");
        Ck("d2i_27", ((int)Id(D(unchecked((long)0x43efffffffffffff)) /* 1.844674407370955e+19 */)).ToString(), "2147483647");
        Ck("d2i_28", ((int)Id(D(unchecked((long)0xbfefae147ae147ae)) /* -0.99 */)).ToString(), "0");
        Ck("d2i_29", ((int)Id(D(unchecked((long)0x406ffccccccccccd)) /* 255.9 */)).ToString(), "255");
        Ck("d2u_30", ((uint)Id(D(unchecked((long)0x0000000000000000)) /* 0.0 */)).ToString(), "0");
        Ck("d2u_31", ((uint)Id(D(unchecked((long)0x8000000000000000)) /* -0.0 */)).ToString(), "0");
        Ck("d2u_32", ((uint)Id(D(unchecked((long)0x3ff0000000000000)) /* 1.0 */)).ToString(), "1");
        Ck("d2u_33", ((uint)Id(D(unchecked((long)0xbff0000000000000)) /* -1.0 */)).ToString(), "0");
        Ck("d2u_34", ((uint)Id(D(unchecked((long)0x3fe0000000000000)) /* 0.5 */)).ToString(), "0");
        Ck("d2u_35", ((uint)Id(D(unchecked((long)0x4000000000000000)) /* 2.0 */)).ToString(), "2");
        Ck("d2u_36", ((uint)Id(D(unchecked((long)0x3fb999999999999a)) /* 0.1 */)).ToString(), "0");
        Ck("d2u_37", ((uint)Id(D(unchecked((long)0x400921fb54442d18)) /* 3.141592653589793 */)).ToString(), "3");
        Ck("d2u_38", ((uint)Id(D(unchecked((long)0x431550f7dca70000)) /* 1500000000000000.0 */)).ToString(), "4294967295");
        Ck("d2u_39", ((uint)Id(D(unchecked((long)0xc01d000000000000)) /* -7.25 */)).ToString(), "0");
        Ck("d2u_40", ((uint)Id(D(unchecked((long)0x7fe1ccf385ebc8a0)) /* 1e+308 */)).ToString(), "4294967295");
        Ck("d2u_41", ((uint)Id(D(unchecked((long)0xffe1ccf385ebc8a0)) /* -1e+308 */)).ToString(), "0");
        Ck("d2u_42", ((uint)Id(D(unchecked((long)0x0000000000000001)) /* 5e-324 */)).ToString(), "0");
        Ck("d2u_43", ((uint)Id(D(unchecked((long)0x0010000000000000)) /* 2.2250738585072014e-308 */)).ToString(), "0");
        Ck("d2u_44", ((uint)Id(D(unchecked((long)0x7ff0000000000000)))).ToString(), "4294967295");
        Ck("d2u_45", ((uint)Id(D(unchecked((long)0xfff0000000000000)))).ToString(), "0");
        Ck("d2u_46", ((uint)Id(D(unchecked((long)0x7ff8000000000000)))).ToString(), "0");
        Ck("d2u_47", ((uint)Id(D(unchecked((long)0x41dfffffffa00000)) /* 2147483646.5 */)).ToString(), "2147483646");
        Ck("d2u_48", ((uint)Id(D(unchecked((long)0x41dfffffffc00000)) /* 2147483647.0 */)).ToString(), "2147483647");
        Ck("d2u_49", ((uint)Id(D(unchecked((long)0x41e0000000000000)) /* 2147483648.0 */)).ToString(), "2147483648");
        Ck("d2u_50", ((uint)Id(D(unchecked((long)0xc1e0000000000000)) /* -2147483648.0 */)).ToString(), "0");
        Ck("d2u_51", ((uint)Id(D(unchecked((long)0xc1e0000000200000)) /* -2147483649.0 */)).ToString(), "0");
        Ck("d2u_52", ((uint)Id(D(unchecked((long)0x41efffffffe00000)) /* 4294967295.0 */)).ToString(), "4294967295");
        Ck("d2u_53", ((uint)Id(D(unchecked((long)0x41f0000000000000)) /* 4294967296.0 */)).ToString(), "4294967295");
        Ck("d2u_54", ((uint)Id(D(unchecked((long)0x43dfffffffffffff)) /* 9.223372036854775e+18 */)).ToString(), "4294967295");
        Ck("d2u_55", ((uint)Id(D(unchecked((long)0xc3e0000000000000)) /* -9.223372036854776e+18 */)).ToString(), "0");
        Ck("d2u_56", ((uint)Id(D(unchecked((long)0x43f0000000000000)) /* 1.8446744073709552e+19 */)).ToString(), "4294967295");
        Ck("d2u_57", ((uint)Id(D(unchecked((long)0x43efffffffffffff)) /* 1.844674407370955e+19 */)).ToString(), "4294967295");
        Ck("d2u_58", ((uint)Id(D(unchecked((long)0xbfefae147ae147ae)) /* -0.99 */)).ToString(), "0");
        Ck("d2u_59", ((uint)Id(D(unchecked((long)0x406ffccccccccccd)) /* 255.9 */)).ToString(), "255");
        Ck("d2l_60", ((long)Id(D(unchecked((long)0x0000000000000000)) /* 0.0 */)).ToString(), "0");
        Ck("d2l_61", ((long)Id(D(unchecked((long)0x8000000000000000)) /* -0.0 */)).ToString(), "0");
        Ck("d2l_62", ((long)Id(D(unchecked((long)0x3ff0000000000000)) /* 1.0 */)).ToString(), "1");
        Ck("d2l_63", ((long)Id(D(unchecked((long)0xbff0000000000000)) /* -1.0 */)).ToString(), "-1");
        Ck("d2l_64", ((long)Id(D(unchecked((long)0x3fe0000000000000)) /* 0.5 */)).ToString(), "0");
        Ck("d2l_65", ((long)Id(D(unchecked((long)0x4000000000000000)) /* 2.0 */)).ToString(), "2");
        Ck("d2l_66", ((long)Id(D(unchecked((long)0x3fb999999999999a)) /* 0.1 */)).ToString(), "0");
        Ck("d2l_67", ((long)Id(D(unchecked((long)0x400921fb54442d18)) /* 3.141592653589793 */)).ToString(), "3");
        Ck("d2l_68", ((long)Id(D(unchecked((long)0x431550f7dca70000)) /* 1500000000000000.0 */)).ToString(), "1500000000000000");
        Ck("d2l_69", ((long)Id(D(unchecked((long)0xc01d000000000000)) /* -7.25 */)).ToString(), "-7");
        Ck("d2l_70", ((long)Id(D(unchecked((long)0x7fe1ccf385ebc8a0)) /* 1e+308 */)).ToString(), "9223372036854775807");
        Ck("d2l_71", ((long)Id(D(unchecked((long)0xffe1ccf385ebc8a0)) /* -1e+308 */)).ToString(), "-9223372036854775808");
        Ck("d2l_72", ((long)Id(D(unchecked((long)0x0000000000000001)) /* 5e-324 */)).ToString(), "0");
        Ck("d2l_73", ((long)Id(D(unchecked((long)0x0010000000000000)) /* 2.2250738585072014e-308 */)).ToString(), "0");
        Ck("d2l_74", ((long)Id(D(unchecked((long)0x7ff0000000000000)))).ToString(), "9223372036854775807");
        Ck("d2l_75", ((long)Id(D(unchecked((long)0xfff0000000000000)))).ToString(), "-9223372036854775808");
        Ck("d2l_76", ((long)Id(D(unchecked((long)0x7ff8000000000000)))).ToString(), "0");
        Ck("d2l_77", ((long)Id(D(unchecked((long)0x41dfffffffa00000)) /* 2147483646.5 */)).ToString(), "2147483646");
        Ck("d2l_78", ((long)Id(D(unchecked((long)0x41dfffffffc00000)) /* 2147483647.0 */)).ToString(), "2147483647");
        Ck("d2l_79", ((long)Id(D(unchecked((long)0x41e0000000000000)) /* 2147483648.0 */)).ToString(), "2147483648");
        Ck("d2l_80", ((long)Id(D(unchecked((long)0xc1e0000000000000)) /* -2147483648.0 */)).ToString(), "-2147483648");
        Ck("d2l_81", ((long)Id(D(unchecked((long)0xc1e0000000200000)) /* -2147483649.0 */)).ToString(), "-2147483649");
        Ck("d2l_82", ((long)Id(D(unchecked((long)0x41efffffffe00000)) /* 4294967295.0 */)).ToString(), "4294967295");
        Ck("d2l_83", ((long)Id(D(unchecked((long)0x41f0000000000000)) /* 4294967296.0 */)).ToString(), "4294967296");
        Ck("d2l_84", ((long)Id(D(unchecked((long)0x43dfffffffffffff)) /* 9.223372036854775e+18 */)).ToString(), "9223372036854774784");
        Ck("d2l_85", ((long)Id(D(unchecked((long)0xc3e0000000000000)) /* -9.223372036854776e+18 */)).ToString(), "-9223372036854775808");
        Ck("d2l_86", ((long)Id(D(unchecked((long)0x43f0000000000000)) /* 1.8446744073709552e+19 */)).ToString(), "9223372036854775807");
        Ck("d2l_87", ((long)Id(D(unchecked((long)0x43efffffffffffff)) /* 1.844674407370955e+19 */)).ToString(), "9223372036854775807");
        Ck("d2l_88", ((long)Id(D(unchecked((long)0xbfefae147ae147ae)) /* -0.99 */)).ToString(), "0");
        Ck("d2l_89", ((long)Id(D(unchecked((long)0x406ffccccccccccd)) /* 255.9 */)).ToString(), "255");
        Ck("d2ul_90", ((ulong)Id(D(unchecked((long)0x0000000000000000)) /* 0.0 */)).ToString(), "0");
        Ck("d2ul_91", ((ulong)Id(D(unchecked((long)0x8000000000000000)) /* -0.0 */)).ToString(), "0");
        Ck("d2ul_92", ((ulong)Id(D(unchecked((long)0x3ff0000000000000)) /* 1.0 */)).ToString(), "1");
        Ck("d2ul_93", ((ulong)Id(D(unchecked((long)0xbff0000000000000)) /* -1.0 */)).ToString(), "0");
        Ck("d2ul_94", ((ulong)Id(D(unchecked((long)0x3fe0000000000000)) /* 0.5 */)).ToString(), "0");
        Ck("d2ul_95", ((ulong)Id(D(unchecked((long)0x4000000000000000)) /* 2.0 */)).ToString(), "2");
        Ck("d2ul_96", ((ulong)Id(D(unchecked((long)0x3fb999999999999a)) /* 0.1 */)).ToString(), "0");
        Ck("d2ul_97", ((ulong)Id(D(unchecked((long)0x400921fb54442d18)) /* 3.141592653589793 */)).ToString(), "3");
        Ck("d2ul_98", ((ulong)Id(D(unchecked((long)0x431550f7dca70000)) /* 1500000000000000.0 */)).ToString(), "1500000000000000");
        Ck("d2ul_99", ((ulong)Id(D(unchecked((long)0xc01d000000000000)) /* -7.25 */)).ToString(), "0");
        Ck("d2ul_100", ((ulong)Id(D(unchecked((long)0x7fe1ccf385ebc8a0)) /* 1e+308 */)).ToString(), "18446744073709551615");
        Ck("d2ul_101", ((ulong)Id(D(unchecked((long)0xffe1ccf385ebc8a0)) /* -1e+308 */)).ToString(), "0");
        Ck("d2ul_102", ((ulong)Id(D(unchecked((long)0x0000000000000001)) /* 5e-324 */)).ToString(), "0");
        Ck("d2ul_103", ((ulong)Id(D(unchecked((long)0x0010000000000000)) /* 2.2250738585072014e-308 */)).ToString(), "0");
        Ck("d2ul_104", ((ulong)Id(D(unchecked((long)0x7ff0000000000000)))).ToString(), "18446744073709551615");
        Ck("d2ul_105", ((ulong)Id(D(unchecked((long)0xfff0000000000000)))).ToString(), "0");
        Ck("d2ul_106", ((ulong)Id(D(unchecked((long)0x7ff8000000000000)))).ToString(), "0");
        Ck("d2ul_107", ((ulong)Id(D(unchecked((long)0x41dfffffffa00000)) /* 2147483646.5 */)).ToString(), "2147483646");
        Ck("d2ul_108", ((ulong)Id(D(unchecked((long)0x41dfffffffc00000)) /* 2147483647.0 */)).ToString(), "2147483647");
        Ck("d2ul_109", ((ulong)Id(D(unchecked((long)0x41e0000000000000)) /* 2147483648.0 */)).ToString(), "2147483648");
        Ck("d2ul_110", ((ulong)Id(D(unchecked((long)0xc1e0000000000000)) /* -2147483648.0 */)).ToString(), "0");
        Ck("d2ul_111", ((ulong)Id(D(unchecked((long)0xc1e0000000200000)) /* -2147483649.0 */)).ToString(), "0");
        Ck("d2ul_112", ((ulong)Id(D(unchecked((long)0x41efffffffe00000)) /* 4294967295.0 */)).ToString(), "4294967295");
        Ck("d2ul_113", ((ulong)Id(D(unchecked((long)0x41f0000000000000)) /* 4294967296.0 */)).ToString(), "4294967296");
        Ck("d2ul_114", ((ulong)Id(D(unchecked((long)0x43dfffffffffffff)) /* 9.223372036854775e+18 */)).ToString(), "9223372036854774784");
        Ck("d2ul_115", ((ulong)Id(D(unchecked((long)0xc3e0000000000000)) /* -9.223372036854776e+18 */)).ToString(), "0");
        Ck("d2ul_116", ((ulong)Id(D(unchecked((long)0x43f0000000000000)) /* 1.8446744073709552e+19 */)).ToString(), "18446744073709551615");
        Ck("d2ul_117", ((ulong)Id(D(unchecked((long)0x43efffffffffffff)) /* 1.844674407370955e+19 */)).ToString(), "18446744073709549568");
        Ck("d2ul_118", ((ulong)Id(D(unchecked((long)0xbfefae147ae147ae)) /* -0.99 */)).ToString(), "0");
        Ck("d2ul_119", ((ulong)Id(D(unchecked((long)0x406ffccccccccccd)) /* 255.9 */)).ToString(), "255");
    }

    static int Main()
    {
        Run();
        P(F_ == 0 ? "ALL PASS" : "FAILURES: " + F_);
        return F_ == 0 ? 0 : 1;
    }
}
