// Copyright (C) 2026 Demerzel Solutions Limited (Nethermind)
// GENERATED by softfloat/gen_tests.py - do not edit by hand.
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

static unsafe class T
{
    [DllImport("__Internal")]
    static extern void sys_write(uint fd, byte* p, nuint n);

    static void P(string s)
    {
        byte[] b = new byte[s.Length + 1];
        for (int i = 0; i < s.Length; i++) b[i] = (byte)s[i];
        b[s.Length] = (byte)10;
        fixed (byte* p = b) sys_write(1, p, (nuint)b.Length);
    }

    static int F_;

    static void Ck(string n, string a, string e)
    {
        if (a != e) { F_++; P("FAIL " + n + ": " + a + " != " + e); }
    }

    static double D(long b) => BitConverter.Int64BitsToDouble(b);
    static float  F(int b)  => BitConverter.Int32BitsToSingle(b);
    static string H(double d) => double.IsNaN(d) ? "nan" : "0x" + BitConverter.DoubleToInt64Bits(d).ToString("x16");
    static string Hf(float f) => float.IsNaN(f) ? "nan" : "0x" + BitConverter.SingleToInt32Bits(f).ToString("x8");

    [MethodImpl(MethodImplOptions.NoInlining)] static double Id(double x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static float  If(float x) => x;
    static void Run()
    {
        Ck("f2d_0", H((double)If(F(unchecked((int)0x00000000)) /* 0.0 */)), "0x0000000000000000");
        Ck("f2d_1", H((double)If(F(unchecked((int)0x80000000)) /* -0.0 */)), "0x8000000000000000");
        Ck("f2d_2", H((double)If(F(unchecked((int)0x3f800000)) /* 1.0 */)), "0x3ff0000000000000");
        Ck("f2d_3", H((double)If(F(unchecked((int)0xbf800000)) /* -1.0 */)), "0xbff0000000000000");
        Ck("f2d_4", H((double)If(F(unchecked((int)0x3f000000)) /* 0.5 */)), "0x3fe0000000000000");
        Ck("f2d_5", H((double)If(F(unchecked((int)0x3dcccccd)) /* 0.10000000149011612 */)), "0x3fb99999a0000000");
        Ck("f2d_6", H((double)If(F(unchecked((int)0x40490fdb)) /* 3.1415927410125732 */)), "0x400921fb60000000");
        Ck("f2d_7", H((double)If(F(unchecked((int)0x58aa87bf)) /* 1500000014041088.0 */)), "0x431550f7e0000000");
        Ck("f2d_8", H((double)If(F(unchecked((int)0xc0e80000)) /* -7.25 */)), "0xc01d000000000000");
        Ck("f2d_9", H((double)If(F(unchecked((int)0x7f61b1e6)) /* 3.0000000054977558e+38 */)), "0x47ec363cc0000000");
        Ck("f2d_10", H((double)If(F(unchecked((int)0xff61b1e6)) /* -3.0000000054977558e+38 */)), "0xc7ec363cc0000000");
        Ck("f2d_11", H((double)If(F(unchecked((int)0x00000001)) /* 1.401298464324817e-45 */)), "0x36a0000000000000");
        Ck("f2d_12", H((double)If(F(unchecked((int)0x00800000)) /* 1.1754943508222875e-38 */)), "0x3810000000000000");
        Ck("f2d_13", H((double)If(F(unchecked((int)0x7f800000)) /* inf */)), "0x7ff0000000000000");
        Ck("f2d_14", H((double)If(F(unchecked((int)0xff800000)) /* -inf */)), "0xfff0000000000000");
        Ck("f2d_15", H((double)If(F(unchecked((int)0x7fc00000)))), "nan");
        Ck("d2f_16", Hf((float)Id(D(unchecked((long)0x0000000000000000)) /* 0.0 */)), "0x00000000");
        Ck("d2f_17", Hf((float)Id(D(unchecked((long)0x8000000000000000)) /* -0.0 */)), "0x80000000");
        Ck("d2f_18", Hf((float)Id(D(unchecked((long)0x3ff0000000000000)) /* 1.0 */)), "0x3f800000");
        Ck("d2f_19", Hf((float)Id(D(unchecked((long)0xbff0000000000000)) /* -1.0 */)), "0xbf800000");
        Ck("d2f_20", Hf((float)Id(D(unchecked((long)0x3fe0000000000000)) /* 0.5 */)), "0x3f000000");
        Ck("d2f_21", Hf((float)Id(D(unchecked((long)0x4000000000000000)) /* 2.0 */)), "0x40000000");
        Ck("d2f_22", Hf((float)Id(D(unchecked((long)0x3fb999999999999a)) /* 0.1 */)), "0x3dcccccd");
        Ck("d2f_23", Hf((float)Id(D(unchecked((long)0x400921fb54442d18)) /* 3.141592653589793 */)), "0x40490fdb");
        Ck("d2f_24", Hf((float)Id(D(unchecked((long)0x431550f7dca70000)) /* 1500000000000000.0 */)), "0x58aa87bf");
        Ck("d2f_25", Hf((float)Id(D(unchecked((long)0xc01d000000000000)) /* -7.25 */)), "0xc0e80000");
        Ck("d2f_26", Hf((float)Id(D(unchecked((long)0x7fe1ccf385ebc8a0)) /* 1e+308 */)), "0x7f800000");
        Ck("d2f_27", Hf((float)Id(D(unchecked((long)0xffe1ccf385ebc8a0)) /* -1e+308 */)), "0xff800000");
        Ck("d2f_28", Hf((float)Id(D(unchecked((long)0x0000000000000001)) /* 5e-324 */)), "0x00000000");
        Ck("d2f_29", Hf((float)Id(D(unchecked((long)0x0010000000000000)) /* 2.2250738585072014e-308 */)), "0x00000000");
        Ck("d2f_30", Hf((float)Id(D(unchecked((long)0x7ff0000000000000)))), "0x7f800000");
        Ck("d2f_31", Hf((float)Id(D(unchecked((long)0xfff0000000000000)))), "0xff800000");
        Ck("d2f_32", Hf((float)Id(D(unchecked((long)0x7ff8000000000000)))), "nan");
        Ck("d2f_33", Hf((float)Id(D(unchecked((long)0x48078287f49c4a1d)) /* 1e+39 */)), "0x7f800000");
        Ck("d2f_34", Hf((float)Id(D(unchecked((long)0xc8078287f49c4a1d)) /* -1e+39 */)), "0xff800000");
        Ck("d2f_35", Hf((float)Id(D(unchecked((long)0x47efffffe54daff8)) /* 3.4028235e+38 */)), "0x7f7fffff");
        Ck("d2f_36", Hf((float)Id(D(unchecked((long)0x47effffff514a7bc)) /* 3.4028236e+38 */)), "0x7f800000");
        Ck("d2f_37", Hf((float)Id(D(unchecked((long)0x37d5c72fb1552d83)) /* 1e-39 */)), "0x000ae398");
        Ck("d2f_38", Hf((float)Id(D(unchecked((long)0x369ff868bf4d956a)) /* 1.4e-45 */)), "0x00000001");
        Ck("d2f_39", Hf((float)Id(D(unchecked((long)0x368ff868bf4d956a)) /* 7e-46 */)), "0x00000000");
        Ck("d2f_40", Hf((float)Id(D(unchecked((long)0x380fffffff9fdba8)) /* 1.17549435e-38 */)), "0x00800000");
        Ck("d2f_41", Hf((float)Id(D(unchecked((long)0x3fd3333333333334)) /* 0.30000000000000004 */)), "0x3e99999a");
        Ck("d2f_42", Hf((float)Id(D(unchecked((long)0x4000000008000000)) /* 2.0000000596046448 */)), "0x40000000");
    }

    static int Main()
    {
        Run();
        P(F_ == 0 ? "ALL PASS" : "FAILURES: " + F_);
        return F_ == 0 ? 0 : 1;
    }
}
