// Copyright (C) 2026 Demerzel Solutions Limited (Nethermind)
// GENERATED by softfloat/gen_tests.py - do not edit by hand.
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

static unsafe class T
{
    [DllImport("__Internal")]
    static extern void sys_write(uint fd, byte* p, nuint n);

    static void P(string s)
    {
        byte[] b = new byte[s.Length + 1];
        for (int i = 0; i < s.Length; i++) b[i] = (byte)s[i];
        b[s.Length] = (byte)10;
        fixed (byte* p = b) sys_write(1, p, (nuint)b.Length);
    }

    static int F_;

    static void Ck(string n, string a, string e)
    {
        if (a != e) { F_++; P("FAIL " + n + ": " + a + " != " + e); }
    }

    static double D(long b) => BitConverter.Int64BitsToDouble(b);
    static float  F(int b)  => BitConverter.Int32BitsToSingle(b);
    static string H(double d) => double.IsNaN(d) ? "nan" : "0x" + BitConverter.DoubleToInt64Bits(d).ToString("x16");
    static string Hf(float f) => float.IsNaN(f) ? "nan" : "0x" + BitConverter.SingleToInt32Bits(f).ToString("x8");

    [MethodImpl(MethodImplOptions.NoInlining)] static double Id(double x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static float  If(float x) => x;

    [MethodImpl(MethodImplOptions.NoInlining)] static int    IdInt(int x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static uint   IdUint(uint x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static long   IdLong(long x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static ulong  IdUlong(ulong x) => x;
    static void Run()
    {
        Ck("i2d_0", H((double)IdInt(0)), "0x0000000000000000");
        Ck("i2f_0", Hf((float)IdInt(0)), "0x00000000");
        Ck("i2d_1", H((double)IdInt(1)), "0x3ff0000000000000");
        Ck("i2f_1", Hf((float)IdInt(1)), "0x3f800000");
        Ck("i2d_2", H((double)IdInt(-1)), "0xbff0000000000000");
        Ck("i2f_2", Hf((float)IdInt(-1)), "0xbf800000");
        Ck("i2d_3", H((double)IdInt(7)), "0x401c000000000000");
        Ck("i2f_3", Hf((float)IdInt(7)), "0x40e00000");
        Ck("i2d_4", H((double)IdInt(-7)), "0xc01c000000000000");
        Ck("i2f_4", Hf((float)IdInt(-7)), "0xc0e00000");
        Ck("i2d_5", H((double)IdInt(2147483647)), "0x41dfffffffc00000");
        Ck("i2f_5", Hf((float)IdInt(2147483647)), "0x4f000000");
        Ck("i2d_6", H((double)IdInt(-2147483648)), "0xc1e0000000000000");
        Ck("i2f_6", Hf((float)IdInt(-2147483648)), "0xcf000000");
        Ck("i2d_7", H((double)IdInt(123456789)), "0x419d6f3454000000");
        Ck("i2f_7", Hf((float)IdInt(123456789)), "0x4ceb79a3");
        Ck("i2d_8", H((double)IdInt(16777217)), "0x4170000010000000");
        Ck("i2f_8", Hf((float)IdInt(16777217)), "0x4b800000");
        Ck("i2d_9", H((double)IdInt(-16777217)), "0xc170000010000000");
        Ck("i2f_9", Hf((float)IdInt(-16777217)), "0xcb800000");
        Ck("i2d_10", H((double)IdUint(0u)), "0x0000000000000000");
        Ck("i2f_10", Hf((float)IdUint(0u)), "0x00000000");
        Ck("i2d_11", H((double)IdUint(1u)), "0x3ff0000000000000");
        Ck("i2f_11", Hf((float)IdUint(1u)), "0x3f800000");
        Ck("i2d_12", H((double)IdUint(7u)), "0x401c000000000000");
        Ck("i2f_12", Hf((float)IdUint(7u)), "0x40e00000");
        Ck("i2d_13", H((double)IdUint(4294967295u)), "0x41efffffffe00000");
        Ck("i2f_13", Hf((float)IdUint(4294967295u)), "0x4f800000");
        Ck("i2d_14", H((double)IdUint(2147483648u)), "0x41e0000000000000");
        Ck("i2f_14", Hf((float)IdUint(2147483648u)), "0x4f000000");
        Ck("i2d_15", H((double)IdUint(16777217u)), "0x4170000010000000");
        Ck("i2f_15", Hf((float)IdUint(16777217u)), "0x4b800000");
        Ck("i2d_16", H((double)IdLong(0L)), "0x0000000000000000");
        Ck("i2f_16", Hf((float)IdLong(0L)), "0x00000000");
        Ck("i2d_17", H((double)IdLong(1L)), "0x3ff0000000000000");
        Ck("i2f_17", Hf((float)IdLong(1L)), "0x3f800000");
        Ck("i2d_18", H((double)IdLong(-1L)), "0xbff0000000000000");
        Ck("i2f_18", Hf((float)IdLong(-1L)), "0xbf800000");
        Ck("i2d_19", H((double)IdLong(9007199254740992L)), "0x4340000000000000");
        Ck("i2f_19", Hf((float)IdLong(9007199254740992L)), "0x5a000000");
        Ck("i2d_20", H((double)IdLong(9007199254740993L)), "0x4340000000000000");
        Ck("i2f_20", Hf((float)IdLong(9007199254740993L)), "0x5a000000");
        Ck("i2d_21", H((double)IdLong(9007199254740991L)), "0x433fffffffffffff");
        Ck("i2f_21", Hf((float)IdLong(9007199254740991L)), "0x5a000000");
        Ck("i2d_22", H((double)IdLong(-9007199254740993L)), "0xc340000000000000");
        Ck("i2f_22", Hf((float)IdLong(-9007199254740993L)), "0xda000000");
        Ck("i2d_23", H((double)IdLong(9223372036854775807L)), "0x43e0000000000000");
        Ck("i2f_23", Hf((float)IdLong(9223372036854775807L)), "0x5f000000");
        Ck("i2d_24", H((double)IdLong(-9223372036854775808L)), "0xc3e0000000000000");
        Ck("i2f_24", Hf((float)IdLong(-9223372036854775808L)), "0xdf000000");
        Ck("i2d_25", H((double)IdLong(4611686018427388928L)), "0x43d0000000000001");
        Ck("i2f_25", Hf((float)IdLong(4611686018427388928L)), "0x5e800000");
        Ck("i2d_26", H((double)IdLong(6004799503160661L)), "0x4335555555555555");
        Ck("i2f_26", Hf((float)IdLong(6004799503160661L)), "0x59aaaaab");
        Ck("i2d_27", H((double)IdUlong(0UL)), "0x0000000000000000");
        Ck("i2f_27", Hf((float)IdUlong(0UL)), "0x00000000");
        Ck("i2d_28", H((double)IdUlong(1UL)), "0x3ff0000000000000");
        Ck("i2f_28", Hf((float)IdUlong(1UL)), "0x3f800000");
        Ck("i2d_29", H((double)IdUlong(18446744073709551615UL)), "0x43f0000000000000");
        Ck("i2f_29", Hf((float)IdUlong(18446744073709551615UL)), "0x5f800000");
        Ck("i2d_30", H((double)IdUlong(9223372036854775808UL)), "0x43e0000000000000");
        Ck("i2f_30", Hf((float)IdUlong(9223372036854775808UL)), "0x5f000000");
        Ck("i2d_31", H((double)IdUlong(9223372036854776832UL)), "0x43e0000000000000");
        Ck("i2f_31", Hf((float)IdUlong(9223372036854776832UL)), "0x5f000000");
        Ck("i2d_32", H((double)IdUlong(9007199254740993UL)), "0x4340000000000000");
        Ck("i2f_32", Hf((float)IdUlong(9007199254740993UL)), "0x5a000000");
        Ck("i2d_33", H((double)IdUlong(18446744073709549568UL)), "0x43efffffffffffff");
        Ck("i2f_33", Hf((float)IdUlong(18446744073709549568UL)), "0x5f800000");
    }

    static int Main()
    {
        Run();
        P(F_ == 0 ? "ALL PASS" : "FAILURES: " + F_);
        return F_ == 0 ? 0 : 1;
    }
}
