// Copyright (C) 2026 Demerzel Solutions Limited (Nethermind)
// GENERATED by softfloat/gen_tests.py - do not edit by hand.
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

static unsafe class T
{
    [DllImport("__Internal")]
    static extern void sys_write(uint fd, byte* p, nuint n);

    static void P(string s)
    {
        byte[] b = new byte[s.Length + 1];
        for (int i = 0; i < s.Length; i++) b[i] = (byte)s[i];
        b[s.Length] = (byte)10;
        fixed (byte* p = b) sys_write(1, p, (nuint)b.Length);
    }

    static int F_;

    static void Ck(string n, string a, string e)
    {
        if (a != e) { F_++; P("FAIL " + n + ": " + a + " != " + e); }
    }

    static double D(long b) => BitConverter.Int64BitsToDouble(b);
    static float  F(int b)  => BitConverter.Int32BitsToSingle(b);
    static string H(double d) => double.IsNaN(d) ? "nan" : "0x" + BitConverter.DoubleToInt64Bits(d).ToString("x16");
    static string Hf(float f) => float.IsNaN(f) ? "nan" : "0x" + BitConverter.SingleToInt32Bits(f).ToString("x8");

    [MethodImpl(MethodImplOptions.NoInlining)] static double Id(double x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static float  If(float x) => x;
    static void Run()
    {
        Ck("f2i_0", ((int)If(F(unchecked((int)0x00000000)) /* 0.0 */)).ToString(), "0");
        Ck("f2i_1", ((int)If(F(unchecked((int)0x80000000)) /* -0.0 */)).ToString(), "0");
        Ck("f2i_2", ((int)If(F(unchecked((int)0x3f800000)) /* 1.0 */)).ToString(), "1");
        Ck("f2i_3", ((int)If(F(unchecked((int)0xbf800000)) /* -1.0 */)).ToString(), "-1");
        Ck("f2i_4", ((int)If(F(unchecked((int)0x3f000000)) /* 0.5 */)).ToString(), "0");
        Ck("f2i_5", ((int)If(F(unchecked((int)0x3dcccccd)) /* 0.10000000149011612 */)).ToString(), "0");
        Ck("f2i_6", ((int)If(F(unchecked((int)0x40490fdb)) /* 3.1415927410125732 */)).ToString(), "3");
        Ck("f2i_7", ((int)If(F(unchecked((int)0x58aa87bf)) /* 1500000014041088.0 */)).ToString(), "2147483647");
        Ck("f2i_8", ((int)If(F(unchecked((int)0xc0e80000)) /* -7.25 */)).ToString(), "-7");
        Ck("f2i_9", ((int)If(F(unchecked((int)0x7f61b1e6)) /* 3.0000000054977558e+38 */)).ToString(), "2147483647");
        Ck("f2i_10", ((int)If(F(unchecked((int)0xff61b1e6)) /* -3.0000000054977558e+38 */)).ToString(), "-2147483648");
        Ck("f2i_11", ((int)If(F(unchecked((int)0x00000001)) /* 1.401298464324817e-45 */)).ToString(), "0");
        Ck("f2i_12", ((int)If(F(unchecked((int)0x00800000)) /* 1.1754943508222875e-38 */)).ToString(), "0");
        Ck("f2i_13", ((int)If(F(unchecked((int)0x7f800000)) /* inf */)).ToString(), "2147483647");
        Ck("f2i_14", ((int)If(F(unchecked((int)0xff800000)) /* -inf */)).ToString(), "-2147483648");
        Ck("f2i_15", ((int)If(F(unchecked((int)0x7fc00000)))).ToString(), "0");
        Ck("f2i_16", ((int)If(F(unchecked((int)0x4f000000)) /* 2147483648.0 */)).ToString(), "2147483647");
        Ck("f2i_17", ((int)If(F(unchecked((int)0xcf000000)) /* -2147483648.0 */)).ToString(), "-2147483648");
        Ck("f2i_18", ((int)If(F(unchecked((int)0x4f800000)) /* 4294967296.0 */)).ToString(), "2147483647");
        Ck("f2i_19", ((int)If(F(unchecked((int)0x5f800000)) /* 1.8446744073709552e+19 */)).ToString(), "2147483647");
        Ck("f2i_20", ((int)If(F(unchecked((int)0x42f7cccd)) /* 123.9000015258789 */)).ToString(), "123");
        Ck("f2i_21", ((int)If(F(unchecked((int)0xc2f7cccd)) /* -123.9000015258789 */)).ToString(), "-123");
        Ck("f2u_22", ((uint)If(F(unchecked((int)0x00000000)) /* 0.0 */)).ToString(), "0");
        Ck("f2u_23", ((uint)If(F(unchecked((int)0x80000000)) /* -0.0 */)).ToString(), "0");
        Ck("f2u_24", ((uint)If(F(unchecked((int)0x3f800000)) /* 1.0 */)).ToString(), "1");
        Ck("f2u_25", ((uint)If(F(unchecked((int)0xbf800000)) /* -1.0 */)).ToString(), "0");
        Ck("f2u_26", ((uint)If(F(unchecked((int)0x3f000000)) /* 0.5 */)).ToString(), "0");
        Ck("f2u_27", ((uint)If(F(unchecked((int)0x3dcccccd)) /* 0.10000000149011612 */)).ToString(), "0");
        Ck("f2u_28", ((uint)If(F(unchecked((int)0x40490fdb)) /* 3.1415927410125732 */)).ToString(), "3");
        Ck("f2u_29", ((uint)If(F(unchecked((int)0x58aa87bf)) /* 1500000014041088.0 */)).ToString(), "4294967295");
        Ck("f2u_30", ((uint)If(F(unchecked((int)0xc0e80000)) /* -7.25 */)).ToString(), "0");
        Ck("f2u_31", ((uint)If(F(unchecked((int)0x7f61b1e6)) /* 3.0000000054977558e+38 */)).ToString(), "4294967295");
        Ck("f2u_32", ((uint)If(F(unchecked((int)0xff61b1e6)) /* -3.0000000054977558e+38 */)).ToString(), "0");
        Ck("f2u_33", ((uint)If(F(unchecked((int)0x00000001)) /* 1.401298464324817e-45 */)).ToString(), "0");
        Ck("f2u_34", ((uint)If(F(unchecked((int)0x00800000)) /* 1.1754943508222875e-38 */)).ToString(), "0");
        Ck("f2u_35", ((uint)If(F(unchecked((int)0x7f800000)) /* inf */)).ToString(), "4294967295");
        Ck("f2u_36", ((uint)If(F(unchecked((int)0xff800000)) /* -inf */)).ToString(), "0");
        Ck("f2u_37", ((uint)If(F(unchecked((int)0x7fc00000)))).ToString(), "0");
        Ck("f2u_38", ((uint)If(F(unchecked((int)0x4f000000)) /* 2147483648.0 */)).ToString(), "2147483648");
        Ck("f2u_39", ((uint)If(F(unchecked((int)0xcf000000)) /* -2147483648.0 */)).ToString(), "0");
        Ck("f2u_40", ((uint)If(F(unchecked((int)0x4f800000)) /* 4294967296.0 */)).ToString(), "4294967295");
        Ck("f2u_41", ((uint)If(F(unchecked((int)0x5f800000)) /* 1.8446744073709552e+19 */)).ToString(), "4294967295");
        Ck("f2u_42", ((uint)If(F(unchecked((int)0x42f7cccd)) /* 123.9000015258789 */)).ToString(), "123");
        Ck("f2u_43", ((uint)If(F(unchecked((int)0xc2f7cccd)) /* -123.9000015258789 */)).ToString(), "0");
        Ck("f2l_44", ((long)If(F(unchecked((int)0x00000000)) /* 0.0 */)).ToString(), "0");
        Ck("f2l_45", ((long)If(F(unchecked((int)0x80000000)) /* -0.0 */)).ToString(), "0");
        Ck("f2l_46", ((long)If(F(unchecked((int)0x3f800000)) /* 1.0 */)).ToString(), "1");
        Ck("f2l_47", ((long)If(F(unchecked((int)0xbf800000)) /* -1.0 */)).ToString(), "-1");
        Ck("f2l_48", ((long)If(F(unchecked((int)0x3f000000)) /* 0.5 */)).ToString(), "0");
        Ck("f2l_49", ((long)If(F(unchecked((int)0x3dcccccd)) /* 0.10000000149011612 */)).ToString(), "0");
        Ck("f2l_50", ((long)If(F(unchecked((int)0x40490fdb)) /* 3.1415927410125732 */)).ToString(), "3");
        Ck("f2l_51", ((long)If(F(unchecked((int)0x58aa87bf)) /* 1500000014041088.0 */)).ToString(), "1500000014041088");
        Ck("f2l_52", ((long)If(F(unchecked((int)0xc0e80000)) /* -7.25 */)).ToString(), "-7");
        Ck("f2l_53", ((long)If(F(unchecked((int)0x7f61b1e6)) /* 3.0000000054977558e+38 */)).ToString(), "9223372036854775807");
        Ck("f2l_54", ((long)If(F(unchecked((int)0xff61b1e6)) /* -3.0000000054977558e+38 */)).ToString(), "-9223372036854775808");
        Ck("f2l_55", ((long)If(F(unchecked((int)0x00000001)) /* 1.401298464324817e-45 */)).ToString(), "0");
        Ck("f2l_56", ((long)If(F(unchecked((int)0x00800000)) /* 1.1754943508222875e-38 */)).ToString(), "0");
        Ck("f2l_57", ((long)If(F(unchecked((int)0x7f800000)) /* inf */)).ToString(), "9223372036854775807");
        Ck("f2l_58", ((long)If(F(unchecked((int)0xff800000)) /* -inf */)).ToString(), "-9223372036854775808");
        Ck("f2l_59", ((long)If(F(unchecked((int)0x7fc00000)))).ToString(), "0");
        Ck("f2l_60", ((long)If(F(unchecked((int)0x4f000000)) /* 2147483648.0 */)).ToString(), "2147483648");
        Ck("f2l_61", ((long)If(F(unchecked((int)0xcf000000)) /* -2147483648.0 */)).ToString(), "-2147483648");
        Ck("f2l_62", ((long)If(F(unchecked((int)0x4f800000)) /* 4294967296.0 */)).ToString(), "4294967296");
        Ck("f2l_63", ((long)If(F(unchecked((int)0x5f800000)) /* 1.8446744073709552e+19 */)).ToString(), "9223372036854775807");
        Ck("f2l_64", ((long)If(F(unchecked((int)0x42f7cccd)) /* 123.9000015258789 */)).ToString(), "123");
        Ck("f2l_65", ((long)If(F(unchecked((int)0xc2f7cccd)) /* -123.9000015258789 */)).ToString(), "-123");
        Ck("f2ul_66", ((ulong)If(F(unchecked((int)0x00000000)) /* 0.0 */)).ToString(), "0");
        Ck("f2ul_67", ((ulong)If(F(unchecked((int)0x80000000)) /* -0.0 */)).ToString(), "0");
        Ck("f2ul_68", ((ulong)If(F(unchecked((int)0x3f800000)) /* 1.0 */)).ToString(), "1");
        Ck("f2ul_69", ((ulong)If(F(unchecked((int)0xbf800000)) /* -1.0 */)).ToString(), "0");
        Ck("f2ul_70", ((ulong)If(F(unchecked((int)0x3f000000)) /* 0.5 */)).ToString(), "0");
        Ck("f2ul_71", ((ulong)If(F(unchecked((int)0x3dcccccd)) /* 0.10000000149011612 */)).ToString(), "0");
        Ck("f2ul_72", ((ulong)If(F(unchecked((int)0x40490fdb)) /* 3.1415927410125732 */)).ToString(), "3");
        Ck("f2ul_73", ((ulong)If(F(unchecked((int)0x58aa87bf)) /* 1500000014041088.0 */)).ToString(), "1500000014041088");
        Ck("f2ul_74", ((ulong)If(F(unchecked((int)0xc0e80000)) /* -7.25 */)).ToString(), "0");
        Ck("f2ul_75", ((ulong)If(F(unchecked((int)0x7f61b1e6)) /* 3.0000000054977558e+38 */)).ToString(), "18446744073709551615");
        Ck("f2ul_76", ((ulong)If(F(unchecked((int)0xff61b1e6)) /* -3.0000000054977558e+38 */)).ToString(), "0");
        Ck("f2ul_77", ((ulong)If(F(unchecked((int)0x00000001)) /* 1.401298464324817e-45 */)).ToString(), "0");
        Ck("f2ul_78", ((ulong)If(F(unchecked((int)0x00800000)) /* 1.1754943508222875e-38 */)).ToString(), "0");
        Ck("f2ul_79", ((ulong)If(F(unchecked((int)0x7f800000)) /* inf */)).ToString(), "18446744073709551615");
        Ck("f2ul_80", ((ulong)If(F(unchecked((int)0xff800000)) /* -inf */)).ToString(), "0");
        Ck("f2ul_81", ((ulong)If(F(unchecked((int)0x7fc00000)))).ToString(), "0");
        Ck("f2ul_82", ((ulong)If(F(unchecked((int)0x4f000000)) /* 2147483648.0 */)).ToString(), "2147483648");
        Ck("f2ul_83", ((ulong)If(F(unchecked((int)0xcf000000)) /* -2147483648.0 */)).ToString(), "0");
        Ck("f2ul_84", ((ulong)If(F(unchecked((int)0x4f800000)) /* 4294967296.0 */)).ToString(), "4294967296");
        Ck("f2ul_85", ((ulong)If(F(unchecked((int)0x5f800000)) /* 1.8446744073709552e+19 */)).ToString(), "18446744073709551615");
        Ck("f2ul_86", ((ulong)If(F(unchecked((int)0x42f7cccd)) /* 123.9000015258789 */)).ToString(), "123");
        Ck("f2ul_87", ((ulong)If(F(unchecked((int)0xc2f7cccd)) /* -123.9000015258789 */)).ToString(), "0");
    }

    static int Main()
    {
        Run();
        P(F_ == 0 ? "ALL PASS" : "FAILURES: " + F_);
        return F_ == 0 ? 0 : 1;
    }
}
