// Copyright (C) 2026 Demerzel Solutions Limited (Nethermind)
// GENERATED by softfloat/gen_tests.py - do not edit by hand.
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

static unsafe class T
{
    [DllImport("__Internal")]
    static extern void sys_write(uint fd, byte* p, nuint n);

    static void P(string s)
    {
        byte[] b = new byte[s.Length + 1];
        for (int i = 0; i < s.Length; i++) b[i] = (byte)s[i];
        b[s.Length] = (byte)10;
        fixed (byte* p = b) sys_write(1, p, (nuint)b.Length);
    }

    static int F_;

    static void Ck(string n, string a, string e)
    {
        if (a != e) { F_++; P("FAIL " + n + ": " + a + " != " + e); }
    }

    static double D(long b) => BitConverter.Int64BitsToDouble(b);
    static float  F(int b)  => BitConverter.Int32BitsToSingle(b);
    static string H(double d) => double.IsNaN(d) ? "nan" : "0x" + BitConverter.DoubleToInt64Bits(d).ToString("x16");
    static string Hf(float f) => float.IsNaN(f) ? "nan" : "0x" + BitConverter.SingleToInt32Bits(f).ToString("x8");

    [MethodImpl(MethodImplOptions.NoInlining)] static double Id(double x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static float  If(float x) => x;
    static void Run()
    {
        double x;
        x = D(unchecked((long)0x0000000000000000)) /* 0.0 */;
        Ck("horner_0", H(((2.0 * Id(x) + 3.0) * Id(x) - 5.0) * Id(x) + 7.0), "0x401c000000000000");
        x = D(unchecked((long)0x3ff0000000000000)) /* 1.0 */;
        Ck("horner_1", H(((2.0 * Id(x) + 3.0) * Id(x) - 5.0) * Id(x) + 7.0), "0x401c000000000000");
        x = D(unchecked((long)0xbff0000000000000)) /* -1.0 */;
        Ck("horner_2", H(((2.0 * Id(x) + 3.0) * Id(x) - 5.0) * Id(x) + 7.0), "0x402a000000000000");
        x = D(unchecked((long)0x3fb999999999999a)) /* 0.1 */;
        Ck("horner_3", H(((2.0 * Id(x) + 3.0) * Id(x) - 5.0) * Id(x) + 7.0), "0x401a20c49ba5e354");
        x = D(unchecked((long)0x400c000000000000)) /* 3.5 */;
        Ck("horner_4", H(((2.0 * Id(x) + 3.0) * Id(x) - 5.0) * Id(x) + 7.0), "0x405c000000000000");
        x = D(unchecked((long)0xc002000000000000)) /* -2.25 */;
        Ck("horner_5", H(((2.0 * Id(x) + 3.0) * Id(x) - 5.0) * Id(x) + 7.0), "0x4025500000000000");
        x = D(unchecked((long)0x4202a05f20000000)) /* 10000000000.0 */;
        Ck("horner_6", H(((2.0 * Id(x) + 3.0) * Id(x) - 5.0) * Id(x) + 7.0), "0x46393e5939b0d040");
        x = D(unchecked((long)0xc202a05f20000000)) /* -10000000000.0 */;
        Ck("horner_7", H(((2.0 * Id(x) + 3.0) * Id(x) - 5.0) * Id(x) + 7.0), "0xc6393e5939904994");
        x = D(unchecked((long)0x40c81cd6e631f8a1)) /* 12345.6789 */;
        Ck("horner_8", H(((2.0 * Id(x) + 3.0) * Id(x) - 5.0) * Id(x) + 7.0), "0x428b62a46e401b60");
        x = D(unchecked((long)0x0000000000000000)) /* 0.0 */;
        Ck("sumsq_9", H(Id(x) * Id(x) + 0.5 * Id(x)), "0x0000000000000000");
        x = D(unchecked((long)0x3ff0000000000000)) /* 1.0 */;
        Ck("sumsq_10", H(Id(x) * Id(x) + 0.5 * Id(x)), "0x3ff8000000000000");
        x = D(unchecked((long)0xbff0000000000000)) /* -1.0 */;
        Ck("sumsq_11", H(Id(x) * Id(x) + 0.5 * Id(x)), "0x3fe0000000000000");
        x = D(unchecked((long)0x3fb999999999999a)) /* 0.1 */;
        Ck("sumsq_12", H(Id(x) * Id(x) + 0.5 * Id(x)), "0x3faeb851eb851eb9");
        x = D(unchecked((long)0x400c000000000000)) /* 3.5 */;
        Ck("sumsq_13", H(Id(x) * Id(x) + 0.5 * Id(x)), "0x402c000000000000");
        x = D(unchecked((long)0xc002000000000000)) /* -2.25 */;
        Ck("sumsq_14", H(Id(x) * Id(x) + 0.5 * Id(x)), "0x400f800000000000");
        x = D(unchecked((long)0x4202a05f20000000)) /* 10000000000.0 */;
        Ck("sumsq_15", H(Id(x) * Id(x) + 0.5 * Id(x)), "0x4415af1d78ba3458");
        x = D(unchecked((long)0xc202a05f20000000)) /* -10000000000.0 */;
        Ck("sumsq_16", H(Id(x) * Id(x) + 0.5 * Id(x)), "0x4415af1d78b0e428");
        x = D(unchecked((long)0x40c81cd6e631f8a1)) /* 12345.6789 */;
        Ck("sumsq_17", H(Id(x) * Id(x) + 0.5 * Id(x)), "0x41a22b8c90aec61d");
        x = D(unchecked((long)0x0000000000000000)) /* 0.0 */;
        Ck("chain_div_18", H(Id(x) / 3.0 / 7.0), "0x0000000000000000");
        x = D(unchecked((long)0x3ff0000000000000)) /* 1.0 */;
        Ck("chain_div_19", H(Id(x) / 3.0 / 7.0), "0x3fa8618618618618");
        x = D(unchecked((long)0xbff0000000000000)) /* -1.0 */;
        Ck("chain_div_20", H(Id(x) / 3.0 / 7.0), "0xbfa8618618618618");
        x = D(unchecked((long)0x3fb999999999999a)) /* 0.1 */;
        Ck("chain_div_21", H(Id(x) / 3.0 / 7.0), "0x3f73813813813813");
        x = D(unchecked((long)0x400c000000000000)) /* 3.5 */;
        Ck("chain_div_22", H(Id(x) / 3.0 / 7.0), "0x3fc5555555555556");
        x = D(unchecked((long)0xc002000000000000)) /* -2.25 */;
        Ck("chain_div_23", H(Id(x) / 3.0 / 7.0), "0xbfbb6db6db6db6db");
        x = D(unchecked((long)0x4202a05f20000000)) /* 10000000000.0 */;
        Ck("chain_div_24", H(Id(x) / 3.0 / 7.0), "0x41bc62170c30c30d");
        x = D(unchecked((long)0xc202a05f20000000)) /* -10000000000.0 */;
        Ck("chain_div_25", H(Id(x) / 3.0 / 7.0), "0xc1bc62170c30c30d");
        x = D(unchecked((long)0x40c81cd6e631f8a1)) /* 12345.6789 */;
        Ck("chain_div_26", H(Id(x) / 3.0 / 7.0), "0x40825f1da3324387");
        x = D(unchecked((long)0x0000000000000000)) /* 0.0 */;
        Ck("mix1_27", H((Id(x) + 0.1) * (Id(x) - 0.1)), "0xbf847ae147ae147c");
        x = D(unchecked((long)0x3ff0000000000000)) /* 1.0 */;
        Ck("mix1_28", H((Id(x) + 0.1) * (Id(x) - 0.1)), "0x3fefae147ae147af");
        x = D(unchecked((long)0xbff0000000000000)) /* -1.0 */;
        Ck("mix1_29", H((Id(x) + 0.1) * (Id(x) - 0.1)), "0x3fefae147ae147af");
        x = D(unchecked((long)0x3fb999999999999a)) /* 0.1 */;
        Ck("mix1_30", H((Id(x) + 0.1) * (Id(x) - 0.1)), "0x0000000000000000");
        x = D(unchecked((long)0x400c000000000000)) /* 3.5 */;
        Ck("mix1_31", H((Id(x) + 0.1) * (Id(x) - 0.1)), "0x40287ae147ae147b");
        x = D(unchecked((long)0xc002000000000000)) /* -2.25 */;
        Ck("mix1_32", H((Id(x) + 0.1) * (Id(x) - 0.1)), "0x401435c28f5c28f6");
        x = D(unchecked((long)0x4202a05f20000000)) /* 10000000000.0 */;
        Ck("mix1_33", H((Id(x) + 0.1) * (Id(x) - 0.1)), "0x4415af1d78b58c40");
        x = D(unchecked((long)0xc202a05f20000000)) /* -10000000000.0 */;
        Ck("mix1_34", H((Id(x) + 0.1) * (Id(x) - 0.1)), "0x4415af1d78b58c40");
        x = D(unchecked((long)0x40c81cd6e631f8a1)) /* 12345.6789 */;
        Ck("mix1_35", H((Id(x) + 0.1) * (Id(x) - 0.1)), "0x41a22b5c56fbdb01");
        x = D(unchecked((long)0x0000000000000000)) /* 0.0 */;
        Ck("mix2_36", H(Id(x) - Id(x) * 0.5 + Id(x) / 4.0), "0x0000000000000000");
        x = D(unchecked((long)0x3ff0000000000000)) /* 1.0 */;
        Ck("mix2_37", H(Id(x) - Id(x) * 0.5 + Id(x) / 4.0), "0x3fe8000000000000");
        x = D(unchecked((long)0xbff0000000000000)) /* -1.0 */;
        Ck("mix2_38", H(Id(x) - Id(x) * 0.5 + Id(x) / 4.0), "0xbfe8000000000000");
        x = D(unchecked((long)0x3fb999999999999a)) /* 0.1 */;
        Ck("mix2_39", H(Id(x) - Id(x) * 0.5 + Id(x) / 4.0), "0x3fb3333333333334");
        x = D(unchecked((long)0x400c000000000000)) /* 3.5 */;
        Ck("mix2_40", H(Id(x) - Id(x) * 0.5 + Id(x) / 4.0), "0x4005000000000000");
        x = D(unchecked((long)0xc002000000000000)) /* -2.25 */;
        Ck("mix2_41", H(Id(x) - Id(x) * 0.5 + Id(x) / 4.0), "0xbffb000000000000");
        x = D(unchecked((long)0x4202a05f20000000)) /* 10000000000.0 */;
        Ck("mix2_42", H(Id(x) - Id(x) * 0.5 + Id(x) / 4.0), "0x41fbf08eb0000000");
        x = D(unchecked((long)0xc202a05f20000000)) /* -10000000000.0 */;
        Ck("mix2_43", H(Id(x) - Id(x) * 0.5 + Id(x) / 4.0), "0xc1fbf08eb0000000");
        x = D(unchecked((long)0x40c81cd6e631f8a1)) /* 12345.6789 */;
        Ck("mix2_44", H(Id(x) - Id(x) * 0.5 + Id(x) / 4.0), "0x40c215a12ca57a79");
        x = D(unchecked((long)0x0000000000000000)) /* 0.0 */;
        Ck("assoc_45", H((Id(x) + 1e16) - 1e16), "0x0000000000000000");
        x = D(unchecked((long)0x3ff0000000000000)) /* 1.0 */;
        Ck("assoc_46", H((Id(x) + 1e16) - 1e16), "0x0000000000000000");
        x = D(unchecked((long)0xbff0000000000000)) /* -1.0 */;
        Ck("assoc_47", H((Id(x) + 1e16) - 1e16), "0x0000000000000000");
        x = D(unchecked((long)0x3fb999999999999a)) /* 0.1 */;
        Ck("assoc_48", H((Id(x) + 1e16) - 1e16), "0x0000000000000000");
        x = D(unchecked((long)0x400c000000000000)) /* 3.5 */;
        Ck("assoc_49", H((Id(x) + 1e16) - 1e16), "0x4010000000000000");
        x = D(unchecked((long)0xc002000000000000)) /* -2.25 */;
        Ck("assoc_50", H((Id(x) + 1e16) - 1e16), "0xc000000000000000");
        x = D(unchecked((long)0x4202a05f20000000)) /* 10000000000.0 */;
        Ck("assoc_51", H((Id(x) + 1e16) - 1e16), "0x4202a05f20000000");
        x = D(unchecked((long)0xc202a05f20000000)) /* -10000000000.0 */;
        Ck("assoc_52", H((Id(x) + 1e16) - 1e16), "0xc202a05f20000000");
        x = D(unchecked((long)0x40c81cd6e631f8a1)) /* 12345.6789 */;
        Ck("assoc_53", H((Id(x) + 1e16) - 1e16), "0x40c81d0000000000");

        double sum = 0.0, comp = 0.0;
        for (int i = 0; i < 100; i++)
        {
            double y = Id(0.1) - comp;
            double t = sum + y;
            comp = (t - sum) - y;
            sum = t;
        }
        Ck("kahan", H(sum), "0x4024000000000000");

        double ps = 0.0;
        for (int i = 0; i < 100; i++) ps += Id(0.1);
        Ck("plainsum", H(ps), "0x4023fffffffffff5");
    }

    static int Main()
    {
        Run();
        P(F_ == 0 ? "ALL PASS" : "FAILURES: " + F_);
        return F_ == 0 ? 0 : 1;
    }
}
