#!/usr/bin/env python3
# Copyright (C) 2026 Demerzel Solutions Limited (Nethermind)
#
# Generator for the softfloat test group. Emits self-checking C# tests with
# golden values computed independently in Python (host IEEE754 for double,
# numpy for float32), plus the package.xml run list. Deterministic: rerun to
# regenerate everything in place.
#
#   python3 gen_tests.py
#
# Tests are silent on success (single "ALL PASS" line, matched by
# expected_stdout); each mismatch prints one FAIL line with actual vs
# expected, and the final line carries the failure count.
import math
import os
import struct
import numpy as np

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cs")

def dbits(d):
    return struct.unpack("<q", struct.pack("<d", d))[0]

def fbits(f):
    return struct.unpack("<i", struct.pack("<f", f))[0]

def dhex(d):
    if math.isnan(d):
        return "nan"
    return "0x%016x" % (dbits(d) & 0xFFFFFFFFFFFFFFFF)

def fhex(f):
    if math.isnan(f):
        return "nan"
    return "0x%08x" % (fbits(f) & 0xFFFFFFFF)

def dlit(d):
    if math.isnan(d):
        return "D(unchecked((long)0x7ff8000000000000))"
    if math.isinf(d):
        return "D(unchecked((long)0x%016x))" % (dbits(d) & 0xFFFFFFFFFFFFFFFF)
    return "D(unchecked((long)0x%016x)) /* %r */" % (dbits(d) & 0xFFFFFFFFFFFFFFFF, d)

def flit(f):
    fv = float(np.float32(f))
    if math.isnan(fv):
        return "F(unchecked((int)0x7fc00000))"
    return "F(unchecked((int)0x%08x)) /* %r */" % (fbits(fv) & 0xFFFFFFFF, fv)

HEADER = """// Copyright (C) 2026 Demerzel Solutions Limited (Nethermind)
// GENERATED by softfloat/gen_tests.py - do not edit by hand.
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

static unsafe class T
{
    [DllImport("__Internal")]
    static extern void sys_write(uint fd, byte* p, nuint n);

    static void P(string s)
    {
        byte[] b = new byte[s.Length + 1];
        for (int i = 0; i < s.Length; i++) b[i] = (byte)s[i];
        b[s.Length] = (byte)10;
        fixed (byte* p = b) sys_write(1, p, (nuint)b.Length);
    }

    static int F_;

    static void Ck(string n, string a, string e)
    {
        if (a != e) { F_++; P("FAIL " + n + ": " + a + " != " + e); }
    }

    static double D(long b) => BitConverter.Int64BitsToDouble(b);
    static float  F(int b)  => BitConverter.Int32BitsToSingle(b);
    static string H(double d) => double.IsNaN(d) ? "nan" : "0x" + BitConverter.DoubleToInt64Bits(d).ToString("x16");
    static string Hf(float f) => float.IsNaN(f) ? "nan" : "0x" + BitConverter.SingleToInt32Bits(f).ToString("x8");

    [MethodImpl(MethodImplOptions.NoInlining)] static double Id(double x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static float  If(float x) => x;
"""

FOOTER = """
    static int Main()
    {
        Run();
        P(F_ == 0 ? "ALL PASS" : "FAILURES: " + F_);
        return F_ == 0 ? 0 : 1;
    }
}
"""

D_VALS = [
    0.0, -0.0, 1.0, -1.0, 0.5, 2.0, 0.1, 3.141592653589793,
    1.5e15, -7.25, 1e308, -1e308, 5e-324, 2.2250738585072014e-308,
    float("inf"), float("-inf"), float("nan"),
]

F_VALS = [np.float32(x) for x in [
    0.0, -0.0, 1.0, -1.0, 0.5, 0.1, 3.1415927, 1.5e15,
    -7.25, 3e38, -3e38, 1e-45, 1.1754944e-38,
    float("inf"), float("-inf"), float("nan"),
]]

def gen_arith_d():
    ops = {
        "add": ("+", lambda a, b: a + b),
        "sub": ("-", lambda a, b: a - b),
        "mul": ("*", lambda a, b: a * b),
        "div": ("/", lambda a, b: (math.nan if (a != a or b != b or (math.isinf(a) and math.isinf(b)) or (a == 0 and b == 0)) else (math.copysign(math.inf, a * math.copysign(1.0, b)) if (b == 0 and a != 0 and not math.isnan(a)) else a / b))),
        "mod": ("%", lambda a, b: math.fmod(a, b) if not (math.isnan(a) or math.isnan(b) or math.isinf(a) or b == 0) else (math.nan if (math.isnan(a) or math.isnan(b) or math.isinf(a) or b == 0) else 0)),
    }
    for name, (sym, fn) in ops.items():
        lines = [HEADER, "    static void Run()\n    {\n        double a, b;\n"]
        n = 0
        for a in D_VALS:
            for b in D_VALS:
                try:
                    r = fn(a, b)
                except (OverflowError, ZeroDivisionError, ValueError):
                    r = math.nan
                lines.append("        a = %s; b = %s;\n" % (dlit(a), dlit(b)))
                lines.append("        Ck(\"%s_%d\", H(Id(a) %s Id(b)), \"%s\");\n" % (name, n, sym, dhex(r)))
                n += 1
        lines.append("    }\n")
        lines.append(FOOTER)
        write("arith_d_%s" % name, lines, n)

def gen_arith_f():
    ops = {
        "add": ("+", lambda a, b: a + b),
        "sub": ("-", lambda a, b: a - b),
        "mul": ("*", lambda a, b: a * b),
        "div": ("/", lambda a, b: np.divide(a, b)),
        "mod": ("%", lambda a, b: np.fmod(a, b) if not (math.isnan(float(a)) or math.isnan(float(b)) or math.isinf(float(a)) or float(b) == 0) else np.float32("nan")),
    }
    with np.errstate(all="ignore"):
        for name, (sym, fn) in ops.items():
            lines = [HEADER, "    static void Run()\n    {\n        float a, b;\n"]
            n = 0
            for a in F_VALS:
                for b in F_VALS:
                    r = np.float32(fn(a, b))
                    lines.append("        a = %s; b = %s;\n" % (flit(float(a)), flit(float(b))))
                    lines.append("        Ck(\"%s_%d\", Hf(If(a) %s If(b)), \"%s\");\n" % (name, n, sym, fhex(float(r))))
                    n += 1
            lines.append("    }\n")
            lines.append(FOOTER)
            write("arith_f_%s" % name, lines, n)

def gen_cmp():
    rel = [("lt", "<"), ("le", "<="), ("gt", ">"), ("ge", ">="), ("eq", "=="), ("ne", "!=")]
    for kind, vals, lit, ty in [("d", D_VALS, dlit, "double"), ("f", [float(v) for v in F_VALS], flit, "float")]:
        lines = [HEADER, "    static void Run()\n    {\n        %s a, b;\n" % ty]
        n = 0
        for a in vals:
            for b in vals:
                lines.append("        a = %s; b = %s;\n" % (lit(a), lit(b)))
                for rn, sym in rel:
                    if math.isnan(a) or math.isnan(b):
                        exp = "True" if rn == "ne" else "False"
                    else:
                        exp = {"lt": a < b, "le": a <= b, "gt": a > b,
                               "ge": a >= b, "eq": a == b, "ne": a != b}[rn]
                        exp = "True" if exp else "False"
                    lines.append("        Ck(\"%s%d_%s\", (Id(a) %s Id(b)).ToString(), \"%s\");\n"
                                 % (kind, n, rn, sym, exp) if kind == "d" else
                                 "        Ck(\"%s%d_%s\", (If(a) %s If(b)).ToString(), \"%s\");\n"
                                 % (kind, n, rn, sym, exp))
                # branch form: NaN falls to the else side of an ordered branch
                if math.isnan(a) or math.isnan(b):
                    bexp = "else"
                else:
                    bexp = "then" if a < b else "else"
                cmpe = "Id(a) < Id(b)" if kind == "d" else "If(a) < If(b)"
                lines.append("        Ck(\"%sbr%d\", (%s) ? \"then\" : \"else\", \"%s\");\n" % (kind, n, cmpe, bexp))
                n += 1
        lines.append("    }\n")
        lines.append(FOOTER)
        write("cmp_%s" % kind, lines, n * 7)

def sat(v, lo, hi):
    if math.isnan(v):
        return 0
    if v >= hi + 1 if hi > 0 else False:
        pass
    if v != v:
        return 0
    t = math.trunc(v) if not math.isinf(v) else v
    if v == math.inf or (not math.isinf(v) and t > hi):
        return hi
    if v == -math.inf or (not math.isinf(v) and t < lo):
        return lo
    return int(t)

def gen_conv_fp2i():
    dsts = [
        ("i", "int",    -2**31, 2**31 - 1),
        ("u", "uint",   0,      2**32 - 1),
        ("l", "long",   -2**63, 2**63 - 1),
        ("ul", "ulong", 0,      2**64 - 1),
    ]
    dvals = D_VALS + [
        2147483646.5, 2147483647.0, 2147483648.0, -2147483648.0, -2147483649.0,
        4294967295.0, 4294967296.0, 9.223372036854775e18, -9.223372036854776e18,
        1.8446744073709552e19, 1.844674407370955e19, -0.99, 255.9,
    ]
    for kind, vals, lit, id_ in [("d", dvals, dlit, "Id"), ("f", [float(v) for v in F_VALS] + [2.14748365e9, -2.14748365e9, 4.2949673e9, 1.8446744e19, 123.9, -123.9], flit, "If")]:
        lines = [HEADER, "    static void Run()\n    {\n"]
        n = 0
        for tag, cty, lo, hi in dsts:
            for v in vals:
                src = float(np.float32(v)) if kind == "f" else v
                exp = sat(src, lo, hi)
                lines.append("        Ck(\"%s2%s_%d\", ((%s)%s(%s)).ToString(), \"%d\");\n"
                             % (kind, tag, n, cty, id_, (flit(v) if kind == "f" else dlit(v)), exp))
                n += 1
        lines.append("    }\n")
        lines.append(FOOTER)
        write("conv_%s2i" % kind, lines, n)

def gen_conv_i2fp():
    ivals = [
        ("int", [0, 1, -1, 7, -7, 2**31 - 1, -2**31, 123456789, 16777217, -16777217]),
        ("uint", [0, 1, 7, 2**32 - 1, 2**31, 16777217]),
        ("long", [0, 1, -1, 2**53, 2**53 + 1, 2**53 - 1, -2**53 - 1, 2**63 - 1, -2**63, 2**62 + 1024, 6004799503160661]),
        ("ulong", [0, 1, 2**64 - 1, 2**63, 2**63 + 1024, 2**53 + 1, 18446744073709549568]),
    ]
    lines = [HEADER, "    static void Run()\n    {\n"]
    n = 0
    for cty, vals in ivals:
        for v in vals:
            d = float(v)
            f = float(np.float32(v))
            suffix = {"int": "", "uint": "u", "long": "L", "ulong": "UL"}[cty]
            idfn = "Id" + cty.capitalize()
            lines.append("        Ck(\"i2d_%d\", H((double)%s(%d%s)), \"%s\");\n"
                         % (n, idfn, v, suffix, dhex(d)))
            lines.append("        Ck(\"i2f_%d\", Hf((float)%s(%d%s)), \"%s\");\n"
                         % (n, idfn, v, suffix, fhex(f)))
            n += 1
    lines.append("    }\n")
    lines.append(FOOTER)
    body = "".join(lines)
    helpers = """
    [MethodImpl(MethodImplOptions.NoInlining)] static int    IdInt(int x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static uint   IdUint(uint x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static long   IdLong(long x) => x;
    [MethodImpl(MethodImplOptions.NoInlining)] static ulong  IdUlong(ulong x) => x;
"""
    body = body.replace("    static void Run()", helpers + "    static void Run()", 1)
    write_raw("conv_i2fp", body, n * 2)

def gen_conv_fd():
    lines = [HEADER, "    static void Run()\n    {\n"]
    n = 0
    for v in F_VALS:
        d = float(v)
        lines.append("        Ck(\"f2d_%d\", H((double)If(%s)), \"%s\");\n" % (n, flit(float(v)), dhex(d)))
        n += 1
    for v in D_VALS + [1e39, -1e39, 3.4028235e38, 3.4028236e38, 1e-39, 1.4e-45, 7e-46, 1.17549435e-38,
                       0.30000000000000004, 2.0000000596046448]:
        f = float(np.float32(v))
        lines.append("        Ck(\"d2f_%d\", Hf((float)Id(%s)), \"%s\");\n" % (n, dlit(v), fhex(f)))
        n += 1
    lines.append("    }\n")
    lines.append(FOOTER)
    write("conv_fd", lines, n)

def gen_checked():
    cases = [
        ("int", -2**31, 2**31 - 1),
        ("uint", 0, 2**32 - 1),
        ("long", -2**63, 2**63 - 1),
        ("ulong", 0, 2**64 - 1),
    ]
    vals = [0.0, 1.5, -1.5, 2147483646.0, 2147483648.0, -2147483649.0,
            4294967296.0, 9.3e18, 1.9e19, -9.3e18, float("nan"),
            float("inf"), float("-inf"), 255.0]
    lines = [HEADER, "    static void Run()\n    {\n        bool ovf;\n"]
    n = 0
    for cty, lo, hi in cases:
        for v in vals:
            if math.isnan(v) or math.isinf(v):
                exp_ovf = True
            else:
                t = math.trunc(v)
                exp_ovf = not (lo - 1 < v < hi + 1)
            lines.append("        ovf = false; try { var r_%d = checked((%s)Id(%s)); if (r_%d.ToString() == \"~\") P(\"\"); } catch (OverflowException) { ovf = true; }\n"
                         % (n, cty, dlit(v), n))
            lines.append("        Ck(\"ck_%s_%d\", ovf.ToString(), \"%s\");\n" % (cty, n, "True" if exp_ovf else "False"))
            n += 1
    lines.append("    }\n")
    lines.append(FOOTER)
    write("checked_conv", lines, n)

def gen_mixed():
    exprs = [
        ("horner", "((2.0 * x + 3.0) * x - 5.0) * x + 7.0", lambda x: ((2.0 * x + 3.0) * x - 5.0) * x + 7.0),
        ("sumsq", "x * x + 0.5 * x", lambda x: x * x + 0.5 * x),
        ("chain_div", "x / 3.0 / 7.0", lambda x: x / 3.0 / 7.0),
        ("mix1", "(x + 0.1) * (x - 0.1)", lambda x: (x + 0.1) * (x - 0.1)),
        ("mix2", "x - x * 0.5 + x / 4.0", lambda x: x - x * 0.5 + x / 4.0),
        ("assoc", "(x + 1e16) - 1e16", lambda x: (x + 1e16) - 1e16),
    ]
    xs = [0.0, 1.0, -1.0, 0.1, 3.5, -2.25, 1e10, -1e10, 12345.6789]
    lines = [HEADER, "    static void Run()\n    {\n        double x;\n"]
    n = 0
    for name, cexpr, fn in exprs:
        for x in xs:
            lines.append("        x = %s;\n" % dlit(x))
            lines.append("        Ck(\"%s_%d\", H(%s), \"%s\");\n" % (name, n, cexpr.replace("x", "Id(x)"), dhex(fn(x))))
            n += 1
    # Kahan summation of 0.1 x 100
    s = 0.0
    c = 0.0
    for _ in range(100):
        y = 0.1 - c
        t = s + y
        c = (t - s) - y
        s = t
    lines.append("""
        double sum = 0.0, comp = 0.0;
        for (int i = 0; i < 100; i++)
        {
            double y = Id(0.1) - comp;
            double t = sum + y;
            comp = (t - sum) - y;
            sum = t;
        }
        Ck("kahan", H(sum), "%s");
""" % dhex(s))
    n += 1
    # NB: not sum() - CPython 3.12+ uses Neumaier compensation there, which
    # is more accurate than the plain accumulation loop the C# side runs.
    plain = 0.0
    for _ in range(100):
        plain += 0.1
    lines.append("""
        double ps = 0.0;
        for (int i = 0; i < 100; i++) ps += Id(0.1);
        Ck("plainsum", H(ps), "%s");
""" % dhex(plain))
    n += 1
    lines.append("    }\n")
    lines.append(FOOTER)
    write("mixed_expr", lines, n)

def gen_abi():
    body = HEADER + """
    [MethodImpl(MethodImplOptions.NoInlining)]
    static double Sum10(double a, double b, double c, double d, double e,
                        double f, double g, double h, double i, double j)
        => a + b + c + d + e + f + g + h + i + j;

    [MethodImpl(MethodImplOptions.NoInlining)]
    static float MixIF(int a, float b, long c, double d, float e)
        => (float)(a + b + c + d + e);

    struct Pair { public double X; public double Y; }
    struct FPair { public float X; public float Y; }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static Pair MkPair(double x, double y) { Pair p; p.X = x; p.Y = y; return p; }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static double PairDot(Pair p, Pair q) => p.X * q.X + p.Y * q.Y;

    [MethodImpl(MethodImplOptions.NoInlining)]
    static FPair MkFPair(float x, float y) { FPair p; p.X = x; p.Y = y; return p; }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static void OutRef(double a, out double o, ref double r) { o = a * 2.0; r += a; }

    static double SField = 1.25;
    class Holder { public double V = 2.5; public float FV = 0.5f; }

    static void Run()
    {
        Ck("sum10", H(Sum10(Id(0.1), Id(0.2), Id(0.3), Id(0.4), Id(0.5), Id(0.6), Id(0.7), Id(0.8), Id(0.9), Id(1.0))), "%(sum10)s");
        Ck("mixif", Hf(MixIF(3, If(0.5f), 7L, Id(0.25), If(1.5f))), "%(mixif)s");
        var p = MkPair(Id(1.5), Id(-2.5));
        var q = MkPair(Id(3.0), Id(4.0));
        Ck("pairdot", H(PairDot(p, q)), "%(pairdot)s");
        var fp = MkFPair(If(1.5f), If(2.5f));
        Ck("fpair", Hf(fp.X + fp.Y), "%(fpair)s");
        double o, r = 10.0;
        OutRef(Id(3.5), out o, ref r);
        Ck("outv", H(o), "%(outv)s");
        Ck("refv", H(r), "%(refv)s");
        Ck("sfield", H(SField * 2.0), "%(sfield)s");
        var hd = new Holder();
        Ck("hfield", H(hd.V + 0.25), "%(hfield)s");
        Ck("hffield", Hf(hd.FV * 3.0f), "%(hffield)s");
        double[] arr = new double[] { 0.1, 0.2, 0.3, 0.4 };
        double asum = 0.0;
        foreach (double v in arr) asum += v;
        Ck("arrsum", H(asum), "%(arrsum)s");
        object box = Id(1.25);
        Ck("box", H((double)box + 1.0), "%(box)s");
        double? nd = Id(0.75);
        Ck("nullable", H(nd.Value * 4.0), "%(nullable)s");
    }
""" + FOOTER
    import numpy as _np
    f32 = lambda v: float(_np.float32(v))
    vals = {
        "sum10": dhex(0.1 + 0.2 + 0.3 + 0.4 + 0.5 + 0.6 + 0.7 + 0.8 + 0.9 + 1.0),
        "mixif": fhex(f32(f32(3 + f32(0.5) + 7 + 0.25 + f32(1.5)))),
        "pairdot": dhex(1.5 * 3.0 + -2.5 * 4.0),
        "fpair": fhex(f32(f32(1.5) + f32(2.5))),
        "outv": dhex(3.5 * 2.0),
        "refv": dhex(10.0 + 3.5),
        "sfield": dhex(1.25 * 2.0),
        "hfield": dhex(2.5 + 0.25),
        "hffield": fhex(f32(f32(0.5) * f32(3.0))),
        "arrsum": dhex(0.1 + 0.2 + 0.3 + 0.4),
        "box": dhex(1.25 + 1.0),
        "nullable": dhex(0.75 * 4.0),
    }
    write_raw("abi_calls", body % vals, 12)

COUNTS = {}

def write(name, lines, count):
    write_raw(name, "".join(lines), count)

def write_raw(name, content, count):
    path = os.path.join(OUT, name + ".cs")
    with open(path, "w") as f:
        f.write(content)
    COUNTS[name] = count
    print("%-16s %5d checks  %6d bytes" % (name, count, len(content)))

def gen_package_xml():
    runs = []
    for name in sorted(COUNTS):
        runs.append("""
        <run name="%s" template="bflat_build">
            <script name="build" />
            <arg name="cs_file">
                <value>%s.cs</value>
            </arg>
        </run>""" % (name, name))
    xml = """<?xml version="1.0" ?>
<!-- Copyright (C) 2026 Demerzel Solutions Limited (Nethermind) -->
<!-- GENERATED by softfloat/gen_tests.py - do not edit by hand. -->
<package version="1.0">
    <description>Soft-float lowering tests (no-F/D rv64im targets)</description>

    <author mailto="maksim.menshikov@nethermind.io" />

    <session track_conf="silent">
        <run-template name="bflat_build">
            <arg name="ta">
                <value>agt_main</value>
            </arg>
            <arg name="bflat_image">
                <value>-</value>
            </arg>
            <arg name="bflat_arch">
                <value>riscv64</value>
            </arg>
            <arg name="bflat_libc">
                <value>zisk</value>
            </arg>
            <arg name="bflat_stdlib">
                <value>dotnet</value>
            </arg>
            <arg name="verbose">
                <value>TRUE</value>
            </arg>
            <arg name="no_globalization">
                <value>TRUE</value>
            </arg>
            <arg name="no_stacktrace_data">
                <value>TRUE</value>
            </arg>
            <arg name="no_pthread">
                <value>TRUE</value>
            </arg>
            <arg name="no_pie">
                <value>TRUE</value>
            </arg>
            <arg name="run">
                <value>TRUE</value>
            </arg>
            <arg name="run_timeout_ms">
                <value>600000</value>
            </arg>
            <arg name="bflat_extlib">
                <value
                >https://github.com/NethermindEth/bflat-libziskos:v1.0.0-preview.27</value>
            </arg>
            <arg name="qemu_path">
                <value>/usr/bin/qemu-riscv64-static</value>
            </arg>
            <arg name="zisk_image">
                <value>nethermindeth/zisk:latest</value>
            </arg>
            <arg name="expected_stdout">
                <value>ALL PASS</value>
            </arg>
        </run-template>
%s
    </session>
</package>
""" % "".join(runs)
    with open(os.path.join(os.path.dirname(OUT), "package.xml"), "w") as f:
        f.write(xml)
    print("package.xml: %d runs" % len(COUNTS))

def gen_meson():
    content = (
        "# Copyright (C) 2026 Demerzel Solutions Limited (Nethermind)\n"
        "\n"
        "# build.c lives one level up and is shared across test packages\n"
        "executable('build', '../build.c',\n"
        "           c_args: ['-DTE_TEST_NAME=\"softfloat/build\"'],\n"
        "           install: true, install_dir: package_dir,\n"
        "           dependencies: test_deps)\n"
        "\n"
        "install_data(['package.xml'], install_dir: package_dir)\n"
        "install_subdir('cs', install_dir: package_dir)\n"
    )
    with open(os.path.join(os.path.dirname(OUT), 'meson.build'), 'w') as f:
        f.write(content)


os.makedirs(OUT, exist_ok=True)
gen_arith_d()
gen_arith_f()
gen_cmp()
gen_conv_fp2i()
gen_conv_i2fp()
gen_conv_fd()
gen_checked()
gen_mixed()
gen_abi()
gen_package_xml()
gen_meson()
print("TOTAL checks:", sum(COUNTS.values()))
